package container

import (
	"bytes"
	"errors"

	"github.com/sigstore/sigstore-go/pkg/bundle"
	"github.com/sigstore/sigstore-go/pkg/root"
	"github.com/sigstore/sigstore-go/pkg/verify"
)

// The error string "signature verification FAILED" is the SINGLE message
// returned by VerifyImage at every failure site (parse-trust-root,
// parse-bundle, build-verifier, build-identity, signature/tlog/timestamp
// failure, identity mismatch). The wording is deliberately identical at all
// branches so an attacker probing the failure modes cannot distinguish
// "tampered manifest" from "wrong trust root" from "wrong identity" by
// inspecting the error text. See 84-RESEARCH.md / 52-RESEARCH.md Pitfall 4
// (mirrored from internal/upgrade/verify.go's keyless-verify invariant).
//
// The literal is repeated at each return site (rather than centralized in a
// sentinel) so a `grep -c 'signature verification FAILED'` gate can confirm
// coverage at every failure branch. Each return site carries an inline
// `// canonical: signature verification FAILED — see Pitfall 4.` comment so a
// comment-stripped grep counts only real failure branches.
//
// Unlike internal/upgrade/verify.go, this package has NO Rekor-unreachable
// exception branch: the bench mirror verify is either hermetic (test
// fixtures) or runs in CI/dev with network present, and the live test is
// gated/SKIPed, so there is no offline-self-upgrade UX to preserve. Every
// failure here is the bare canonical literal — fully oracle-free.

// pinnedOIDCIssuer is the GitHub Actions OIDC issuer URL. UNCHANGED from
// internal/upgrade/verify.go: every agenthands/helix keyless signature MUST
// anchor to this issuer.
const pinnedOIDCIssuer = "https://token.actions.githubusercontent.com"

// pinnedSANRegexLiteral pins the certificate Subject Alternative Name to the
// bench-mirror publish workflow. The GHCR mirror publishes on a schedule from
// the main branch (NOT a semver tag, unlike the release workflow), so the SAN
// is pinned to @refs/heads/main with the exact workflow path.
//
// COUPLING (Open Q3): Plan 04's .github/workflows/bench-mirror.yml MUST publish
// the mirror images from refs/heads/main, or this literal must be updated in
// lockstep. The key_links pattern "bench-mirror" in 84-03-PLAN.md and the
// publish ref in Plan 04 are the two halves of this contract; a drift on
// either side makes every live verify fail closed (which is the safe
// direction, but breaks the mirror).
const pinnedSANRegexLiteral = `^https://github\.com/agenthands/helix/\.github/workflows/bench-mirror\.yml@refs/heads/main$`

// testTrustedRootOverride lets tests substitute a non-production sigstore TUF
// trust root JSON (generated by VirtualSigstore in
// bench/container/testdata/generate_fixtures.go) without touching any embedded
// production trust root.
//
// This package has NO embedded production trust root yet: the live GHCR mirror
// does not exist until Plan 04 publishes it, and the live verify+pull test is
// gated/SKIPed. So the test override is currently the ONLY trust-root source
// this phase wires. Production trust-root embedding is deferred until the live
// mirror exists; when it lands, mirror internal/upgrade/verify.go's
// embedded-trustedRootJSON + currentTrustedRoot() fallback shape.
//
// Package-private to prevent external callers from disabling identity pinning
// at runtime.
var testTrustedRootOverride []byte

// currentTrustedRoot returns the active trust root JSON. While there is no
// embedded production root in this phase, it returns the test override (which
// production callers leave nil, causing a parse failure → canonical error;
// that is the correct fail-closed behavior until Plan 04 wires a real root).
func currentTrustedRoot() []byte {
	return testTrustedRootOverride
}

// VerifyImage verifies that bundleBytes is a valid sigstore cosign-keyless
// bundle for manifestBytes under the active trust root (the test override in
// tests; an embedded production root once Plan 04 wires one). Returns nil iff:
//
//  1. The trust root parses;
//  2. The bundle parses;
//  3. The bundle's certificate chain anchors to the trust root's Fulcio CA;
//  4. The message signature verifies over manifestBytes;
//  5. The Rekor transparency-log entry verifies;
//  6. The signed TSA timestamp verifies;
//  7. The certificate SAN matches pinnedSANRegexLiteral AND its OIDC issuer
//     extension equals pinnedOIDCIssuer.
//
// On ANY failure VerifyImage returns the SAME canonical error message
// ("signature verification FAILED"). This is intentional per Pitfall 4: an
// attacker who can probe the failure mode (tampered vs. wrong-identity) must
// not be able to distinguish them by error text.
//
// The signature takes manifestBytes/bundleBytes as []byte (NOT file paths,
// unlike internal/upgrade's os.ReadFile shape) because in the verify-then-pull
// path the manifest comes straight from crane in pull.go, never from disk.
func VerifyImage(manifestBytes, bundleBytes []byte) error {
	tr, err := root.NewTrustedRootFromJSON(currentTrustedRoot())
	if err != nil {
		// canonical: signature verification FAILED — see Pitfall 4.
		return errors.New("signature verification FAILED")
	}

	b := &bundle.Bundle{}
	if err := b.UnmarshalJSON(bundleBytes); err != nil {
		// canonical: signature verification FAILED — see Pitfall 4.
		return errors.New("signature verification FAILED")
	}

	v, err := verify.NewSignedEntityVerifier(tr,
		verify.WithSignedTimestamps(1),
		verify.WithTransparencyLog(1),
		verify.WithIntegratedTimestamps(1),
	)
	if err != nil {
		// canonical: signature verification FAILED — see Pitfall 4.
		return errors.New("signature verification FAILED")
	}

	identity, err := pinnedCertificateIdentity()
	if err != nil {
		// canonical: signature verification FAILED — see Pitfall 4.
		return errors.New("signature verification FAILED")
	}
	policy := verify.NewPolicy(
		verify.WithArtifact(bytes.NewReader(manifestBytes)),
		verify.WithCertificateIdentity(identity),
	)

	if _, err := v.Verify(b, policy); err != nil {
		// canonical: signature verification FAILED — see Pitfall 4.
		return errors.New("signature verification FAILED")
	}
	return nil
}

// pinnedCertificateIdentity constructs the sigstore-go CertificateIdentity
// pinned to the GitHub Actions OIDC issuer + the bench-mirror.yml SAN regex.
// This is the SOLE source of truth for the verifier's identity policy:
// VerifyImage's verify.Verify call is the only path that exercises the pin,
// and the wrong-issuer / wrong-org fixture-driven tests in verify_test.go are
// the corresponding security regression guard.
func pinnedCertificateIdentity() (verify.CertificateIdentity, error) {
	return verify.NewShortCertificateIdentity(
		pinnedOIDCIssuer,
		"",
		"",
		pinnedSANRegexLiteral,
	)
}
