package cli

import (
	"regexp"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// helixVerbTokenRe extracts the kebab verb after a `helix ` mention in the
// priming matrix (e.g. "helix read-file" → "read-file"). It anchors on the
// `helix ` prefix so prose words are not mistaken for verbs.
var helixVerbTokenRe = regexp.MustCompile(`helix ([a-z][a-z0-9-]*)`)

// TestSessionStartPriming is the STEER-02 contract for the SessionStart priming
// surface. It asserts the terse "use X not Y" matrix is:
//   - non-empty and sourced from the single `primingMatrix` constant,
//   - byte-capped à la SKILL-04 (≤ primingMatrixMaxBytes),
//   - NOT the 32 KB reference banner nor the full SKILL body (idle-cost bound),
//   - a pure/deterministic function (no daemon dial, no I/O — cannot fail the
//     session; fail-open),
//   - drift-free: every `helix <verb>` token it cites resolves to a REAL frozen
//     verb in VerbToolNames() (so a future verb rename surfaces here, not silently).
func TestSessionStartPriming(t *testing.T) {
	text := sessionPrimingText()

	// Non-empty + sourced from the single constant.
	require.NotEmpty(t, text, "sessionPrimingText() must return the terse priming matrix")
	require.Equal(t, primingMatrix, text,
		"sessionPrimingText() must return the primingMatrix constant verbatim (single source of truth, no runtime drift)")

	// SKILL-04-style byte cap.
	require.LessOrEqualf(t, len(text), primingMatrixMaxBytes,
		"priming matrix is %d bytes, exceeds the %d-byte cap (STEER-02 idle-cost bound)",
		len(text), primingMatrixMaxBytes)

	// It IS a use-X-not-Y matrix: it mentions the helix CLI.
	assert.Contains(t, text, "helix ", "the priming matrix must cite `helix` verbs")

	// It is NOT the 32 KB generated reference and NOT the whole SKILL body.
	assert.NotContains(t, text, "Code generated by helix-refgen",
		"priming must NOT inline the generated reference banner (idle-cost bloat)")
	assert.Lessf(t, len(text), len(EmbeddedSkillBody()),
		"priming must be terser than the full SKILL body (got %d vs SKILL %d bytes)",
		len(text), len(EmbeddedSkillBody()))

	// Pure / deterministic: repeated calls return identical bytes (no I/O, no dial).
	assert.Equal(t, text, sessionPrimingText(), "sessionPrimingText() must be deterministic (pure, fail-open)")

	// Drift guard: every cited `helix <verb>` is a real frozen verb. The matrix
	// uses kebab verbs; VerbToolNames() returns snake_case tool names — map
	// `-`→`_` to compare (mirrors the kebab/snake convention of the frozen surface).
	registered := make(map[string]bool)
	for _, name := range VerbToolNames() {
		registered[name] = true
	}
	matches := helixVerbTokenRe.FindAllStringSubmatch(text, -1)
	require.NotEmpty(t, matches, "the priming matrix must cite at least one `helix <verb>`")
	for _, m := range matches {
		kebab := m[1]
		snake := strings.ReplaceAll(kebab, "-", "_")
		assert.Truef(t, registered[snake],
			"priming matrix cites `helix %s` which is not a real frozen verb (VerbToolNames()); a renamed/invented verb must surface here, not silently drift",
			kebab)
	}
}
