package cli

import (
	"encoding/json"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestEmbeddedReference asserts the new AGENT-01 accessor surfaces the SAME
// generated reference.md bytes already embedded for Claude, so non-Claude agents
// can consume the one generated source (no per-agent bespoke engine). The
// reference carries a generator banner the terse SKILL.md never does, proving it
// is reference.md (not SKILL.md), and it differs from EmbeddedSkillBody().
func TestEmbeddedReference(t *testing.T) {
	ref := EmbeddedReference()
	if strings.TrimSpace(ref) == "" {
		t.Fatal("EmbeddedReference() is empty")
	}
	// The generator banner proves this is reference.md, not SKILL.md.
	if !strings.Contains(ref, "Code generated by helix-refgen") {
		t.Error("EmbeddedReference() does not carry the helix-refgen banner; not reference.md")
	}
	// A known verb section header proves it is the per-verb reference.
	if !strings.Contains(ref, "helix go-to-definition") {
		t.Error("EmbeddedReference() missing a known verb section (helix go-to-definition)")
	}
	// It must differ from the SKILL.md body (no accidental aliasing).
	if ref == EmbeddedSkillBody() {
		t.Error("EmbeddedReference() returned the SKILL.md body; expected reference.md")
	}
}

// TestWriteAgentInstructions exercises the idempotent sentinel-delimited writer:
// empty-dir append, user-content preservation, idempotent re-run (no duplicate
// block), the 32-KiB cap (appended block trimmed to a pointer, never user
// content), path containment, and atomic write (no .tmp sibling). The idempotency
// and cap sub-cases are the anti-vacuity teeth — a duplicated block or a clobbered
// user file MUST fail.
func TestWriteAgentInstructions(t *testing.T) {
	const maxBytes = 32 * 1024

	t.Run("empty-dir-appends-block", func(t *testing.T) {
		dir := t.TempDir()
		path := filepath.Join(dir, "AGENTS.md")
		require.NoError(t, writeAgentInstructions(path, agentInstructionBody(), maxBytes))

		data, err := os.ReadFile(path)
		require.NoError(t, err)
		content := string(data)
		assert.Contains(t, content, helixBlockBegin, "block begin sentinel must be present")
		assert.Contains(t, content, helixBlockEnd, "block end sentinel must be present")
	})

	t.Run("preserves-user-content", func(t *testing.T) {
		dir := t.TempDir()
		path := filepath.Join(dir, "AGENTS.md")
		userContent := "# my notes\n\nSome existing project guidance the user hand-wrote.\n"
		require.NoError(t, os.WriteFile(path, []byte(userContent), 0644))

		require.NoError(t, writeAgentInstructions(path, agentInstructionBody(), maxBytes))

		data, err := os.ReadFile(path)
		require.NoError(t, err)
		content := string(data)
		// User bytes survive verbatim.
		assert.Contains(t, content, "# my notes", "user heading must survive")
		assert.Contains(t, content, "Some existing project guidance the user hand-wrote.", "user body must survive")
		// The Helix block is appended AFTER the user content.
		userIdx := strings.Index(content, "# my notes")
		blockIdx := strings.Index(content, helixBlockBegin)
		require.NotEqual(t, -1, blockIdx, "Helix block must be present")
		assert.Greater(t, blockIdx, userIdx, "Helix block must come after user content")
	})

	t.Run("idempotent-rerun-no-duplicate", func(t *testing.T) {
		dir := t.TempDir()
		path := filepath.Join(dir, "AGENTS.md")
		userContent := "# my notes\n"
		require.NoError(t, os.WriteFile(path, []byte(userContent), 0644))

		require.NoError(t, writeAgentInstructions(path, agentInstructionBody(), maxBytes))
		require.NoError(t, writeAgentInstructions(path, agentInstructionBody(), maxBytes))

		data, err := os.ReadFile(path)
		require.NoError(t, err)
		content := string(data)
		// EXACTLY ONE block after two writes — a duplicated block is the anti-vacuity failure.
		assert.Equal(t, 1, strings.Count(content, helixBlockBegin), "exactly one begin sentinel after re-run")
		assert.Equal(t, 1, strings.Count(content, helixBlockEnd), "exactly one end sentinel after re-run")
		// User content still present exactly once.
		assert.Equal(t, 1, strings.Count(content, "# my notes"), "user content present exactly once")
	})

	t.Run("32-KiB-cap-trims-block-not-user-content", func(t *testing.T) {
		dir := t.TempDir()
		path := filepath.Join(dir, "AGENTS.md")
		// A representative near-32-KiB user AGENTS.md.
		userBody := "# big user agents file\n\n" + strings.Repeat("Documented project convention line that the user wrote.\n", 560)
		require.Greater(t, len(userBody), 30*1024, "fixture must be near the cap to exercise trimming")
		require.Less(t, len(userBody), maxBytes, "fixture must still fit under the cap before the append")
		require.NoError(t, os.WriteFile(path, []byte(userBody), 0644))

		require.NoError(t, writeAgentInstructions(path, agentInstructionBody(), maxBytes))

		data, err := os.ReadFile(path)
		require.NoError(t, err)
		// The WHOLE file stays at or under the cap.
		assert.LessOrEqual(t, len(data), maxBytes, "final file must stay within the 32-KiB cap")
		content := string(data)
		// The user content is fully preserved (trimming hit the appended block, not user bytes).
		assert.Contains(t, content, "# big user agents file", "user heading preserved under cap")
		assert.Equal(t, 560, strings.Count(content, "Documented project convention line that the user wrote.\n"),
			"every user line preserved; only the appended block was trimmed")
		// A block (even trimmed to a pointer) is still present.
		assert.Contains(t, content, helixBlockBegin, "a (trimmed) Helix block must still be appended")
	})

	t.Run("cap-too-small-errors-rather-than-truncating-user", func(t *testing.T) {
		dir := t.TempDir()
		path := filepath.Join(dir, "AGENTS.md")
		userBody := strings.Repeat("x", 1000) + "\n"
		require.NoError(t, os.WriteFile(path, []byte(userBody), 0644))

		// A cap smaller than even the user content + the minimal pointer cannot fit.
		err := writeAgentInstructions(path, agentInstructionBody(), 500)
		require.Error(t, err, "an impossible cap must error, never truncate user bytes")
		// The user file is untouched (no partial write).
		data, readErr := os.ReadFile(path)
		require.NoError(t, readErr)
		assert.Equal(t, userBody, string(data), "user content must be untouched when the write errors")
	})

	t.Run("path-containment-refuses-escape", func(t *testing.T) {
		dir := t.TempDir()
		// A raw, UNCLEANED destination carrying ".." traversal segments — the shape
		// a malicious/garbled config value would produce. The guard must refuse it
		// before any write rather than letting it resolve outside its dir.
		escaping := dir + string(filepath.Separator) + "sub" +
			string(filepath.Separator) + ".." + string(filepath.Separator) + ".." +
			string(filepath.Separator) + "escaped" + string(filepath.Separator) + "AGENTS.md"
		err := writeAgentInstructions(escaping, agentInstructionBody(), maxBytes)
		require.Error(t, err, "a ..-escaping destination must be refused")
		// No write happened at the escaped location.
		_, statErr := os.Stat(filepath.Join(filepath.Dir(dir), "escaped", "AGENTS.md"))
		assert.True(t, os.IsNotExist(statErr), "no file written outside the contained dir")
	})

	t.Run("atomic-no-tmp-sibling", func(t *testing.T) {
		dir := t.TempDir()
		path := filepath.Join(dir, "AGENTS.md")
		require.NoError(t, writeAgentInstructions(path, agentInstructionBody(), maxBytes))

		// No ".tmp" sibling remains after a successful write.
		entries, err := os.ReadDir(dir)
		require.NoError(t, err)
		for _, e := range entries {
			assert.False(t, strings.HasSuffix(e.Name(), ".tmp"), "no .tmp sibling should remain: %s", e.Name())
		}
	})
}

// --- Task 3: Codex/Gemini/generic registrars (AGENT-03) ---

// findHookArtifacts walks root and returns the relative paths of any file whose
// name looks like a hook config (a JSON file named *hooks*.json). Used to prove
// Gemini produces NO hook artifact.
func findHookArtifacts(t *testing.T, root string) []string {
	t.Helper()
	var found []string
	err := filepath.WalkDir(root, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		name := strings.ToLower(d.Name())
		if strings.Contains(name, "hook") && strings.HasSuffix(name, ".json") {
			rel, _ := filepath.Rel(root, p)
			found = append(found, rel)
		}
		return nil
	})
	require.NoError(t, err)
	return found
}

// TestWriteCodexHooks asserts the Codex hooks.json writer emits a JSON file whose
// PreToolUse handler invokes `<bin> nudge` (the ONE engine, no second steering
// output), with type:"command", and NEVER a deny default. The bytes are pinned to
// the documented Codex hooks convention (additionalContext envelope, type:command
// handlers; STACK.md A1).
func TestWriteCodexHooks(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "hooks.json")
	bin := "/usr/local/bin/helix"
	require.NoError(t, writeCodexHooks(path, bin))

	data, err := os.ReadFile(path)
	require.NoError(t, err)

	// It parses as JSON.
	var parsed map[string]any
	require.NoError(t, json.Unmarshal(data, &parsed), "hooks.json must be valid JSON")

	// The serialized form invokes the nudge engine via the helix binary.
	raw := string(data)
	assert.Contains(t, raw, bin, "hooks.json command must reference the helix binary path")
	assert.Contains(t, raw, "nudge", "hooks.json command must invoke the nudge engine")
	assert.Contains(t, raw, "PreToolUse", "hooks.json must register a PreToolUse handler")
	assert.Contains(t, raw, "command", `hooks.json must use type:"command" handlers`)

	// Locked anti-feature: NEVER a deny-by-default.
	assert.NotContains(t, raw, "permissionDecision", "Codex hook must be advisory only — no permissionDecision")
	assert.NotContains(t, raw, "deny", "Codex hook must never set a deny default")

	// No .tmp sibling remains (atomic write).
	entries, err := os.ReadDir(dir)
	require.NoError(t, err)
	for _, e := range entries {
		assert.False(t, strings.HasSuffix(e.Name(), ".tmp"), "no .tmp sibling should remain: %s", e.Name())
	}

	// Idempotent / byte-stable re-run.
	require.NoError(t, writeCodexHooks(path, bin))
	data2, err := os.ReadFile(path)
	require.NoError(t, err)
	assert.Equal(t, data, data2, "re-running writeCodexHooks must be byte-stable")
}

// codexPreToolUseEntries is a test helper extracting the PreToolUse matcher
// array from a Codex hooks.json file. It fails the test if the schema is not the
// expected {"hooks":{"PreToolUse":[...]}} shape.
func codexPreToolUseEntries(t *testing.T, path string) []any {
	t.Helper()
	data, err := os.ReadFile(path)
	require.NoError(t, err)
	var parsed map[string]any
	require.NoError(t, json.Unmarshal(data, &parsed), "hooks.json must be valid JSON")
	hooks, ok := parsed["hooks"].(map[string]any)
	require.True(t, ok, "hooks.json must have a top-level hooks object")
	pre, ok := hooks["PreToolUse"].([]any)
	require.True(t, ok, "hooks.json must have a PreToolUse array")
	return pre
}

// countHelixNudgeEntries counts PreToolUse matcher objects that are our
// structural Helix entry: matcher=="Bash" AND command is a 2-element array whose
// last element is "nudge".
func countHelixNudgeEntries(entries []any) int {
	n := 0
	for _, e := range entries {
		m, ok := e.(map[string]any)
		if !ok {
			continue
		}
		if m["matcher"] != "Bash" {
			continue
		}
		hooksArr, ok := m["hooks"].([]any)
		if !ok || len(hooksArr) == 0 {
			continue
		}
		for _, h := range hooksArr {
			hm, ok := h.(map[string]any)
			if !ok {
				continue
			}
			cmd, ok := hm["command"].([]any)
			if !ok || len(cmd) != 2 {
				continue
			}
			if cmd[len(cmd)-1] == "nudge" {
				n++
			}
		}
	}
	return n
}

// TestWriteCodexHooksMergePreservesOthers asserts that writing into an existing
// Codex hooks.json MERGES our PreToolUse Bash→nudge entry while preserving (a) an
// unrelated event (Stop) and (b) an unrelated PreToolUse matcher (non-Bash). This
// is the core no-clobber goal of AGENT-03.
func TestWriteCodexHooksMergePreservesOthers(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "hooks.json")
	bin := "/usr/local/bin/helix"

	// Pre-existing user hooks.json in valid Codex shape with an unrelated Stop
	// event and an unrelated (non-Bash) PreToolUse matcher.
	existing := map[string]any{
		"hooks": map[string]any{
			"Stop": []any{
				map[string]any{
					"hooks": []any{
						map[string]any{
							"type":    "command",
							"command": []any{"/opt/user/cleanup", "run"},
							"timeout": 10,
						},
					},
				},
			},
			"PreToolUse": []any{
				map[string]any{
					"matcher": "Edit",
					"hooks": []any{
						map[string]any{
							"type":    "command",
							"command": []any{"/opt/user/lint", "check"},
							"timeout": 7,
						},
					},
				},
			},
		},
	}
	raw, err := json.MarshalIndent(existing, "", "  ")
	require.NoError(t, err)
	require.NoError(t, os.WriteFile(path, raw, 0644))

	require.NoError(t, writeCodexHooks(path, bin))

	// No backup should be created for a valid Codex-shaped file.
	_, statErr := os.Stat(path + ".bak")
	assert.True(t, os.IsNotExist(statErr), "valid Codex hooks.json must not be backed up")

	out, err := os.ReadFile(path)
	require.NoError(t, err)
	var parsed map[string]any
	require.NoError(t, json.Unmarshal(out, &parsed))
	hooks := parsed["hooks"].(map[string]any)

	// (a) the unrelated Stop event survives.
	stop, ok := hooks["Stop"].([]any)
	require.True(t, ok, "Stop event must survive the merge")
	require.Len(t, stop, 1)
	assert.Contains(t, string(out), "/opt/user/cleanup", "user Stop hook command must survive")

	// (b) the unrelated PreToolUse matcher survives AND our Bash→nudge entry is added.
	pre := codexPreToolUseEntries(t, path)
	assert.Contains(t, string(out), "/opt/user/lint", "unrelated PreToolUse matcher must survive")
	assert.Contains(t, string(out), bin, "our nudge entry must reference the binary")
	assert.Equal(t, 1, countHelixNudgeEntries(pre), "exactly one Helix Bash→nudge entry after merge")
}

// TestWriteCodexHooksIdempotentRefreshesStalePath asserts that re-running over an
// existing file containing a Bash→nudge entry with a STALE first-element binary
// path refreshes that path to the current binaryPath and does NOT duplicate the
// entry, and that a subsequent run is byte-identical.
func TestWriteCodexHooksIdempotentRefreshesStalePath(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "hooks.json")
	bin := "/usr/local/bin/helix"
	stale := "/old/path/helix"

	existing := map[string]any{
		"hooks": map[string]any{
			"PreToolUse": []any{
				map[string]any{
					"matcher": "Bash",
					"hooks": []any{
						map[string]any{
							"type":    "command",
							"command": []any{stale, "nudge"},
							"timeout": 5,
						},
					},
				},
			},
		},
	}
	raw, err := json.MarshalIndent(existing, "", "  ")
	require.NoError(t, err)
	require.NoError(t, os.WriteFile(path, raw, 0644))

	require.NoError(t, writeCodexHooks(path, bin))

	out, err := os.ReadFile(path)
	require.NoError(t, err)
	pre := codexPreToolUseEntries(t, path)
	assert.Equal(t, 1, countHelixNudgeEntries(pre), "stale entry must be refreshed, not duplicated")
	assert.Contains(t, string(out), bin, "the refreshed entry must use the current binary path")
	assert.NotContains(t, string(out), stale, "the stale binary path must be gone")

	// Second run is byte-identical.
	require.NoError(t, writeCodexHooks(path, bin))
	out2, err := os.ReadFile(path)
	require.NoError(t, err)
	assert.Equal(t, out, out2, "merge re-run must be byte-stable")
}

// TestWriteCodexHooksLegacyForeignBackedUp asserts that an existing file NOT in
// the {"hooks":...} shape (legacy Claude-style top-level event keys, or invalid
// JSON) is preserved at <path>.bak and replaced with a valid Codex file rather
// than silently clobbered.
func TestWriteCodexHooksLegacyForeignBackedUp(t *testing.T) {
	bin := "/usr/local/bin/helix"

	t.Run("legacy claude-style top-level event keys", func(t *testing.T) {
		dir := t.TempDir()
		path := filepath.Join(dir, "hooks.json")
		legacy := []byte(`{"SessionStart":[{"matcher":"startup"}]}`)
		require.NoError(t, os.WriteFile(path, legacy, 0644))

		require.NoError(t, writeCodexHooks(path, bin))

		// Original preserved at .bak.
		bak, err := os.ReadFile(path + ".bak")
		require.NoError(t, err, "legacy file must be backed up to .bak")
		assert.Equal(t, legacy, bak, ".bak must contain the original bytes verbatim")

		// New file is valid Codex shape with our entry.
		pre := codexPreToolUseEntries(t, path)
		assert.Equal(t, 1, countHelixNudgeEntries(pre), "fresh Codex file must carry our entry")
	})

	t.Run("invalid JSON", func(t *testing.T) {
		dir := t.TempDir()
		path := filepath.Join(dir, "hooks.json")
		junk := []byte("not json at all {{{")
		require.NoError(t, os.WriteFile(path, junk, 0644))

		require.NoError(t, writeCodexHooks(path, bin))

		bak, err := os.ReadFile(path + ".bak")
		require.NoError(t, err, "unparseable file must be backed up to .bak")
		assert.Equal(t, junk, bak, ".bak must contain the original bytes verbatim")

		pre := codexPreToolUseEntries(t, path)
		assert.Equal(t, 1, countHelixNudgeEntries(pre), "fresh Codex file must carry our entry")

		// And the new file contains no deny default (advisory-only invariant).
		out, err := os.ReadFile(path)
		require.NoError(t, err)
		assert.NotContains(t, string(out), "permissionDecision")
		assert.NotContains(t, string(out), "deny")
	})
}

// TestCodexRegistrar asserts CodexRegistrar.Register writes BOTH an AGENTS.md
// (sentinel-delimited Helix block, idempotent) and a Codex hooks.json invoking
// `<bin> nudge`, advisory-only.
func TestCodexRegistrar(t *testing.T) {
	tmp := t.TempDir()
	cfg := RegistrationConfig{
		ProjectDir: tmp,
		BinaryPath: "/path/to/helix",
		Printer:    &SetupPrinter{},
	}
	r := &CodexRegistrar{}
	require.Equal(t, "codex", r.Name())
	require.NotEmpty(t, r.Description())

	require.NoError(t, r.Register(cfg))

	// (a) AGENTS.md exists under tmp with the sentinel block.
	agentsPath := filepath.Join(tmp, "AGENTS.md")
	agentsData, err := os.ReadFile(agentsPath)
	require.NoError(t, err, "Codex AGENTS.md must be written")
	assert.Contains(t, string(agentsData), helixBlockBegin, "AGENTS.md must carry the Helix block")
	assert.LessOrEqual(t, len(agentsData), 32*1024, "Codex AGENTS.md must stay within the 32-KiB cap")

	// (b) hooks.json exists under the project .codex dir.
	hooksPath := filepath.Join(tmp, ".codex", "hooks.json")
	hooksData, err := os.ReadFile(hooksPath)
	require.NoError(t, err, "Codex hooks.json must be written")

	// (c) the hooks.json command invokes `helix nudge` (one engine).
	var parsed map[string]any
	require.NoError(t, json.Unmarshal(hooksData, &parsed), "hooks.json must be valid JSON")
	assert.Contains(t, string(hooksData), cfg.BinaryPath, "hooks command must reference the binary")
	assert.Contains(t, string(hooksData), "nudge", "hooks command must invoke nudge")

	// (d) no deny default.
	assert.NotContains(t, string(hooksData), "permissionDecision", "no deny default")

	// Idempotent re-run: no duplicate AGENTS.md block.
	require.NoError(t, r.Register(cfg))
	agentsData2, err := os.ReadFile(agentsPath)
	require.NoError(t, err)
	assert.Equal(t, 1, strings.Count(string(agentsData2), helixBlockBegin), "re-run must not duplicate the block")
}

// TestGeminiNoHookArtifact asserts GeminiCLIRegistrar.Register writes a GEMINI.md
// with the Helix block AND produces NO hook artifact anywhere under tmp (Gemini
// has no PreToolUse-equivalent; fabricating one is the locked anti-feature).
func TestGeminiNoHookArtifact(t *testing.T) {
	tmp := t.TempDir()
	cfg := RegistrationConfig{
		ProjectDir: tmp,
		BinaryPath: "/path/to/helix",
		Printer:    &SetupPrinter{},
	}
	r := &GeminiCLIRegistrar{}
	require.NoError(t, r.Register(cfg))

	// GEMINI.md exists with the Helix block.
	geminiPath := filepath.Join(tmp, "GEMINI.md")
	data, err := os.ReadFile(geminiPath)
	require.NoError(t, err, "GEMINI.md must be written")
	assert.Contains(t, string(data), helixBlockBegin, "GEMINI.md must carry the Helix block")

	// NO hook artifact anywhere under tmp.
	hooks := findHookArtifacts(t, tmp)
	assert.Empty(t, hooks, "Gemini must produce NO hook artifact (locked anti-feature); found: %v", hooks)

	// Idempotent re-run: no duplicate block.
	require.NoError(t, r.Register(cfg))
	data2, err := os.ReadFile(geminiPath)
	require.NoError(t, err)
	assert.Equal(t, 1, strings.Count(string(data2), helixBlockBegin), "re-run must not duplicate the block")
}

// TestGenericRegistrarWritesInstructionFile asserts GenericRegistrar.Register
// writes the generic AGENTS.md (no hook), and honors DryRun (no write).
func TestGenericRegistrarWritesInstructionFile(t *testing.T) {
	t.Run("writes-agents-md", func(t *testing.T) {
		tmp := t.TempDir()
		cfg := RegistrationConfig{ProjectDir: tmp, BinaryPath: "/path/to/helix", Printer: &SetupPrinter{}}
		require.NoError(t, (&GenericRegistrar{}).Register(cfg))

		data, err := os.ReadFile(filepath.Join(tmp, "AGENTS.md"))
		require.NoError(t, err, "generic AGENTS.md must be written")
		assert.Contains(t, string(data), helixBlockBegin)

		// No hook artifact.
		assert.Empty(t, findHookArtifacts(t, tmp), "generic must produce no hook")
	})

	t.Run("dry-run-writes-nothing", func(t *testing.T) {
		tmp := t.TempDir()
		cfg := RegistrationConfig{ProjectDir: tmp, BinaryPath: "/path/to/helix", DryRun: true, Printer: &SetupPrinter{DryRun: true}}
		require.NoError(t, (&GenericRegistrar{}).Register(cfg))
		_, err := os.Stat(filepath.Join(tmp, "AGENTS.md"))
		assert.True(t, os.IsNotExist(err), "dry-run must not write AGENTS.md")
	})
}

// TestCodexInValidArgsAndRegistry asserts codex is a resolvable setup target and
// vscode/jetbrains/opencode remain teardown-only (not flipped).
func TestCodexInValidArgsAndRegistry(t *testing.T) {
	// In the registry.
	reg := clientRegistry()
	_, ok := reg["codex"]
	assert.True(t, ok, "codex must be in clientRegistry()")

	// In ValidArgs.
	cmd := newSetupCommand()
	assert.Contains(t, cmd.ValidArgs, "codex", "codex must be in setup ValidArgs")

	// vscode/jetbrains/opencode remain teardown-only: their Register writes no
	// instruction file.
	for _, name := range []string{"vscode", "jetbrains", "opencode"} {
		tmp := t.TempDir()
		cfg := RegistrationConfig{ProjectDir: tmp, BinaryPath: "/path/to/helix", Printer: &SetupPrinter{}}
		require.NoError(t, reg[name].Register(cfg), "%s Register", name)
		_, err := os.Stat(filepath.Join(tmp, "AGENTS.md"))
		assert.True(t, os.IsNotExist(err), "%s must remain teardown-only (no AGENTS.md)", name)
		_, err = os.Stat(filepath.Join(tmp, "GEMINI.md"))
		assert.True(t, os.IsNotExist(err), "%s must remain teardown-only (no GEMINI.md)", name)
	}
}
