package cli

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestEmbeddedReference asserts the new AGENT-01 accessor surfaces the SAME
// generated reference.md bytes already embedded for Claude, so non-Claude agents
// can consume the one generated source (no per-agent bespoke engine). The
// reference carries a generator banner the terse SKILL.md never does, proving it
// is reference.md (not SKILL.md), and it differs from EmbeddedSkillBody().
func TestEmbeddedReference(t *testing.T) {
	ref := EmbeddedReference()
	if strings.TrimSpace(ref) == "" {
		t.Fatal("EmbeddedReference() is empty")
	}
	// The generator banner proves this is reference.md, not SKILL.md.
	if !strings.Contains(ref, "Code generated by helix-refgen") {
		t.Error("EmbeddedReference() does not carry the helix-refgen banner; not reference.md")
	}
	// A known verb section header proves it is the per-verb reference.
	if !strings.Contains(ref, "helix go-to-definition") {
		t.Error("EmbeddedReference() missing a known verb section (helix go-to-definition)")
	}
	// It must differ from the SKILL.md body (no accidental aliasing).
	if ref == EmbeddedSkillBody() {
		t.Error("EmbeddedReference() returned the SKILL.md body; expected reference.md")
	}
}

// TestWriteAgentInstructions exercises the idempotent sentinel-delimited writer:
// empty-dir append, user-content preservation, idempotent re-run (no duplicate
// block), the 32-KiB cap (appended block trimmed to a pointer, never user
// content), path containment, and atomic write (no .tmp sibling). The idempotency
// and cap sub-cases are the anti-vacuity teeth — a duplicated block or a clobbered
// user file MUST fail.
func TestWriteAgentInstructions(t *testing.T) {
	const maxBytes = 32 * 1024

	t.Run("empty-dir-appends-block", func(t *testing.T) {
		dir := t.TempDir()
		path := filepath.Join(dir, "AGENTS.md")
		require.NoError(t, writeAgentInstructions(path, agentInstructionBody(), maxBytes))

		data, err := os.ReadFile(path)
		require.NoError(t, err)
		content := string(data)
		assert.Contains(t, content, helixBlockBegin, "block begin sentinel must be present")
		assert.Contains(t, content, helixBlockEnd, "block end sentinel must be present")
	})

	t.Run("preserves-user-content", func(t *testing.T) {
		dir := t.TempDir()
		path := filepath.Join(dir, "AGENTS.md")
		userContent := "# my notes\n\nSome existing project guidance the user hand-wrote.\n"
		require.NoError(t, os.WriteFile(path, []byte(userContent), 0644))

		require.NoError(t, writeAgentInstructions(path, agentInstructionBody(), maxBytes))

		data, err := os.ReadFile(path)
		require.NoError(t, err)
		content := string(data)
		// User bytes survive verbatim.
		assert.Contains(t, content, "# my notes", "user heading must survive")
		assert.Contains(t, content, "Some existing project guidance the user hand-wrote.", "user body must survive")
		// The Helix block is appended AFTER the user content.
		userIdx := strings.Index(content, "# my notes")
		blockIdx := strings.Index(content, helixBlockBegin)
		require.NotEqual(t, -1, blockIdx, "Helix block must be present")
		assert.Greater(t, blockIdx, userIdx, "Helix block must come after user content")
	})

	t.Run("idempotent-rerun-no-duplicate", func(t *testing.T) {
		dir := t.TempDir()
		path := filepath.Join(dir, "AGENTS.md")
		userContent := "# my notes\n"
		require.NoError(t, os.WriteFile(path, []byte(userContent), 0644))

		require.NoError(t, writeAgentInstructions(path, agentInstructionBody(), maxBytes))
		require.NoError(t, writeAgentInstructions(path, agentInstructionBody(), maxBytes))

		data, err := os.ReadFile(path)
		require.NoError(t, err)
		content := string(data)
		// EXACTLY ONE block after two writes — a duplicated block is the anti-vacuity failure.
		assert.Equal(t, 1, strings.Count(content, helixBlockBegin), "exactly one begin sentinel after re-run")
		assert.Equal(t, 1, strings.Count(content, helixBlockEnd), "exactly one end sentinel after re-run")
		// User content still present exactly once.
		assert.Equal(t, 1, strings.Count(content, "# my notes"), "user content present exactly once")
	})

	t.Run("32-KiB-cap-trims-block-not-user-content", func(t *testing.T) {
		dir := t.TempDir()
		path := filepath.Join(dir, "AGENTS.md")
		// A representative near-32-KiB user AGENTS.md.
		userBody := "# big user agents file\n\n" + strings.Repeat("Documented project convention line that the user wrote.\n", 560)
		require.Greater(t, len(userBody), 30*1024, "fixture must be near the cap to exercise trimming")
		require.Less(t, len(userBody), maxBytes, "fixture must still fit under the cap before the append")
		require.NoError(t, os.WriteFile(path, []byte(userBody), 0644))

		require.NoError(t, writeAgentInstructions(path, agentInstructionBody(), maxBytes))

		data, err := os.ReadFile(path)
		require.NoError(t, err)
		// The WHOLE file stays at or under the cap.
		assert.LessOrEqual(t, len(data), maxBytes, "final file must stay within the 32-KiB cap")
		content := string(data)
		// The user content is fully preserved (trimming hit the appended block, not user bytes).
		assert.Contains(t, content, "# big user agents file", "user heading preserved under cap")
		assert.Equal(t, 560, strings.Count(content, "Documented project convention line that the user wrote.\n"),
			"every user line preserved; only the appended block was trimmed")
		// A block (even trimmed to a pointer) is still present.
		assert.Contains(t, content, helixBlockBegin, "a (trimmed) Helix block must still be appended")
	})

	t.Run("cap-too-small-errors-rather-than-truncating-user", func(t *testing.T) {
		dir := t.TempDir()
		path := filepath.Join(dir, "AGENTS.md")
		userBody := strings.Repeat("x", 1000) + "\n"
		require.NoError(t, os.WriteFile(path, []byte(userBody), 0644))

		// A cap smaller than even the user content + the minimal pointer cannot fit.
		err := writeAgentInstructions(path, agentInstructionBody(), 500)
		require.Error(t, err, "an impossible cap must error, never truncate user bytes")
		// The user file is untouched (no partial write).
		data, readErr := os.ReadFile(path)
		require.NoError(t, readErr)
		assert.Equal(t, userBody, string(data), "user content must be untouched when the write errors")
	})

	t.Run("path-containment-refuses-escape", func(t *testing.T) {
		dir := t.TempDir()
		// A raw, UNCLEANED destination carrying ".." traversal segments — the shape
		// a malicious/garbled config value would produce. The guard must refuse it
		// before any write rather than letting it resolve outside its dir.
		escaping := dir + string(filepath.Separator) + "sub" +
			string(filepath.Separator) + ".." + string(filepath.Separator) + ".." +
			string(filepath.Separator) + "escaped" + string(filepath.Separator) + "AGENTS.md"
		err := writeAgentInstructions(escaping, agentInstructionBody(), maxBytes)
		require.Error(t, err, "a ..-escaping destination must be refused")
		// No write happened at the escaped location.
		_, statErr := os.Stat(filepath.Join(filepath.Dir(dir), "escaped", "AGENTS.md"))
		assert.True(t, os.IsNotExist(statErr), "no file written outside the contained dir")
	})

	t.Run("atomic-no-tmp-sibling", func(t *testing.T) {
		dir := t.TempDir()
		path := filepath.Join(dir, "AGENTS.md")
		require.NoError(t, writeAgentInstructions(path, agentInstructionBody(), maxBytes))

		// No ".tmp" sibling remains after a successful write.
		entries, err := os.ReadDir(dir)
		require.NoError(t, err)
		for _, e := range entries {
			assert.False(t, strings.HasSuffix(e.Name(), ".tmp"), "no .tmp sibling should remain: %s", e.Name())
		}
	})
}
