// Code generated by helix-cligen; DO NOT EDIT.
// Regenerate with: go run ./cmd/helix-cligen

package cli

// verbSpecs is the generated verb->tool catalog: one entry per callable
// tool in the live registry, flattened onto the root command grouped by
// capability. Tools registered via the dynamic map[string]any handler
// (AddSkillTool) carry no derivable flags and appear with an empty flag set.
var verbSpecs = map[string]verbSpec{
	"analyze-blast-radius": {
		toolName: "analyze_blast_radius",
		short:    "Run the analyze_blast_radius tool against the warm daemon",
		groupID:  "navigation",
		flags: []verbFlag{
			{name: "path", toolArg: "path", kind: flagString, required: true, help: "File path"},
			{name: "line", toolArg: "line", kind: flagInt, required: true, help: "Line number (1-indexed, matches editor display)"},
			{name: "column", toolArg: "column", kind: flagInt, required: true, help: "Column number (1-indexed, matches editor display)"},
		},
	},
	"create-file": {
		toolName: "create_file",
		short:    "Run the create_file tool against the warm daemon",
		groupID:  "fileops",
		flags: []verbFlag{
			{name: "path", toolArg: "path", kind: flagString, required: true, help: "File path to create (relative to workspace root)"},
			{name: "content", toolArg: "content", kind: flagString, required: true, help: "File content to write"},
		},
	},
	"delete-memory": {
		toolName: "delete_memory",
		short:    "Run the delete_memory tool against the warm daemon",
		groupID:  "memory",
		flags:    nil,
	},
	"edit-memory": {
		toolName: "edit_memory",
		short:    "Run the edit_memory tool against the warm daemon",
		groupID:  "memory",
		flags:    nil,
	},
	"explain-cluster": {
		toolName: "explain_cluster",
		short:    "Run the explain_cluster tool against the warm daemon",
		groupID:  "repomap",
		flags: []verbFlag{
			{name: "cluster-id", toolArg: "cluster_id", kind: flagString, required: true, help: "opaque cluster token from get_cluster_map"},
			{name: "max-members", toolArg: "max_members", kind: flagInt, required: false, help: "maximum members to return (default 200, max 1000)"},
		},
	},
	"explain-symbol-deep": {
		toolName: "explain_symbol_deep",
		short:    "Run the explain_symbol_deep tool against the warm daemon",
		groupID:  "repomap",
		flags: []verbFlag{
			{name: "seed-json", toolArg: "seed", kind: flagJSON, required: true, help: "seed symbol — symbol_id OR (file_path AND symbol_name)"},
		},
	},
	"find-files": {
		toolName: "find_files",
		short:    "Run the find_files tool against the warm daemon",
		groupID:  "fileops",
		flags: []verbFlag{
			{name: "pattern", toolArg: "pattern", kind: flagString, required: true, help: "Glob pattern to match files (supports ** for recursive)"},
		},
	},
	"find-implementations": {
		toolName: "find_implementations",
		short:    "Run the find_implementations tool against the warm daemon",
		groupID:  "navigation",
		flags: []verbFlag{
			{name: "path", toolArg: "path", kind: flagString, required: true, help: "File path"},
			{name: "line", toolArg: "line", kind: flagInt, required: true, help: "Line number (1-indexed, matches editor display)"},
			{name: "column", toolArg: "column", kind: flagInt, required: true, help: "Column number (1-indexed, matches editor display)"},
		},
	},
	"find-references": {
		toolName: "find_references",
		short:    "Run the find_references tool against the warm daemon",
		groupID:  "navigation",
		flags: []verbFlag{
			{name: "path", toolArg: "path", kind: flagString, required: true, help: "File path"},
			{name: "line", toolArg: "line", kind: flagInt, required: true, help: "Line number (1-indexed, matches editor display)"},
			{name: "column", toolArg: "column", kind: flagInt, required: true, help: "Column number (1-indexed, matches editor display)"},
			{name: "include-declaration", toolArg: "include_declaration", kind: flagBool, required: false, help: "Include the declaration itself in results"},
		},
	},
	"find-related-symbols": {
		toolName: "find_related_symbols",
		short:    "Run the find_related_symbols tool against the warm daemon",
		groupID:  "repomap",
		flags: []verbFlag{
			{name: "seed-json", toolArg: "seed", kind: flagJSON, required: true, help: "seed symbol — symbol_id OR (file_path AND symbol_name)"},
			{name: "k", toolArg: "k", kind: flagInt, required: false, help: "top-N cap; default 20; clamped to [1, 100]"},
			{name: "paths", toolArg: "paths", kind: flagStringSlice, required: false, help: "strict-subset filter on RESULT defining files; the seed itself is NOT constrained"},
		},
	},
	"format-code": {
		toolName: "format_code",
		short:    "Run the format_code tool against the warm daemon",
		groupID:  "diagnostics",
		flags: []verbFlag{
			{name: "path", toolArg: "path", kind: flagString, required: true, help: "File path to format"},
			{name: "tab-size", toolArg: "tab_size", kind: flagInt, required: false, help: "Tab size (default: 4)"},
			{name: "use-spaces", toolArg: "use_spaces", kind: flagBool, required: false, help: "Use spaces instead of tabs (default: true)"},
		},
	},
	"fuzzy-edit": {
		toolName: "fuzzy_edit",
		short:    "Run the fuzzy_edit tool against the warm daemon",
		groupID:  "fileops",
		flags: []verbFlag{
			{name: "path", toolArg: "path", kind: flagString, required: true, help: "File path (relative to workspace root)"},
			{name: "search", toolArg: "search", kind: flagString, required: true, help: "Text to search for (fuzzy matched with 4-strategy cascade: exact, whitespace-normalized, indentation-flexible)"},
			{name: "replacement", toolArg: "replacement", kind: flagString, required: true, help: "Replacement text"},
			{name: "disable-ellipsis", toolArg: "disable_ellipsis", kind: flagBool, required: false, help: "Disable ... ellipsis segmentation (default false, meaning ellipsis is enabled)"},
			{name: "receipts", toolArg: "receipts", kind: flagStringSlice, required: false, help: "Receipt IDs from prior find_references / analyze_blast_radius / get_context / get_repo_map / verify_edit calls. Required by guardrails (Phase 66 GUARD-03) for destructive operations on referenced or public-API symbols. Empty array when no receipts apply."},
		},
	},
	"get-call-hierarchy": {
		toolName: "get_call_hierarchy",
		short:    "Run the get_call_hierarchy tool against the warm daemon",
		groupID:  "navigation",
		flags: []verbFlag{
			{name: "path", toolArg: "path", kind: flagString, required: true, help: "File path"},
			{name: "line", toolArg: "line", kind: flagInt, required: true, help: "Line number (1-indexed, matches editor display)"},
			{name: "column", toolArg: "column", kind: flagInt, required: true, help: "Column number (1-indexed, matches editor display)"},
			{name: "direction", toolArg: "direction", kind: flagString, required: false, help: "incoming, outgoing, or both (default: both)"},
		},
	},
	"get-change-impact-graph": {
		toolName: "get_change_impact_graph",
		short:    "Run the get_change_impact_graph tool against the warm daemon",
		groupID:  "repomap",
		flags: []verbFlag{
			{name: "seed-json", toolArg: "seed", kind: flagJSON, required: true, help: "seed"},
			{name: "max-depth", toolArg: "max_depth", kind: flagInt, required: false, help: "BFS expansion depth (default 2, max 5)"},
			{name: "edge-kinds", toolArg: "edge_kinds", kind: flagStringSlice, required: false, help: "optional edge kind filter (MCP surface enum values)"},
		},
	},
	"get-cluster-map": {
		toolName: "get_cluster_map",
		short:    "Run the get_cluster_map tool against the warm daemon",
		groupID:  "repomap",
		flags: []verbFlag{
			{name: "projection", toolArg: "projection", kind: flagString, required: false, help: "cluster projection — defaults to 'weak_components'"},
			{name: "top-n", toolArg: "top_n", kind: flagInt, required: false, help: "number of top clusters to return (default 20, max 100)"},
		},
	},
	"get-code-actions": {
		toolName: "get_code_actions",
		short:    "Run the get_code_actions tool against the warm daemon",
		groupID:  "diagnostics",
		flags: []verbFlag{
			{name: "path", toolArg: "path", kind: flagString, required: true, help: "File path"},
			{name: "line", toolArg: "line", kind: flagInt, required: true, help: "Line number (1-indexed)"},
			{name: "column", toolArg: "column", kind: flagInt, required: true, help: "Column number (1-indexed)"},
			{name: "end-line", toolArg: "end_line", kind: flagInt, required: false, help: "End line for range selection"},
			{name: "end-column", toolArg: "end_column", kind: flagInt, required: false, help: "End column for range selection"},
		},
	},
	"get-context": {
		toolName: "get_context",
		short:    "Run the get_context tool against the warm daemon",
		groupID:  "repomap",
		flags:    nil,
	},
	"get-diagnostics": {
		toolName: "get_diagnostics",
		short:    "Run the get_diagnostics tool against the warm daemon",
		groupID:  "diagnostics",
		flags: []verbFlag{
			{name: "path", toolArg: "path", kind: flagString, required: true, help: "File path to check diagnostics for"},
		},
	},
	"get-health": {
		toolName: "get_health",
		short:    "Run the get_health tool against the warm daemon",
		groupID:  "memory",
		flags: []verbFlag{
			{name: "verbose", toolArg: "verbose", kind: flagBool, required: false, help: "Show all language servers including healthy ones. Default false returns only unhealthy LSes."},
		},
	},
	"get-hover-info": {
		toolName: "get_hover_info",
		short:    "Run the get_hover_info tool against the warm daemon",
		groupID:  "navigation",
		flags: []verbFlag{
			{name: "path", toolArg: "path", kind: flagString, required: true, help: "File path"},
			{name: "line", toolArg: "line", kind: flagInt, required: true, help: "Line number (1-indexed, matches editor display)"},
			{name: "column", toolArg: "column", kind: flagInt, required: true, help: "Column number (1-indexed, matches editor display)"},
		},
	},
	"get-repo-map": {
		toolName: "get_repo_map",
		short:    "Run the get_repo_map tool against the warm daemon",
		groupID:  "repomap",
		flags:    nil,
	},
	"get-semantic-context": {
		toolName: "get_semantic_context",
		short:    "Run the get_semantic_context tool against the warm daemon",
		groupID:  "repomap",
		flags: []verbFlag{
			{name: "task", toolArg: "task", kind: flagString, required: false, help: "natural-language task description"},
			{name: "files", toolArg: "files", kind: flagStringSlice, required: false, help: "anchor files for personalized PageRank"},
			{name: "symbols", toolArg: "symbols", kind: flagStringSlice, required: false, help: "anchor symbol IDs"},
			{name: "max-tokens", toolArg: "max_tokens", kind: flagInt, required: false, help: "token budget (default 2048; clamped to [64, 32768])"},
			{name: "freshness-mode", toolArg: "freshness_mode", kind: flagString, required: false, help: "allow_stale | require_current | validate_live"},
		},
	},
	"get-semantic-graph-status": {
		toolName: "get_semantic_graph_status",
		short:    "Run the get_semantic_graph_status tool against the warm daemon",
		groupID:  "repomap",
		flags:    nil,
	},
	"get-symbol-overview": {
		toolName: "get_symbol_overview",
		short:    "Run the get_symbol_overview tool against the warm daemon",
		groupID:  "navigation",
		flags: []verbFlag{
			{name: "path", toolArg: "path", kind: flagString, required: true, help: "File path for symbol outline"},
		},
	},
	"get-token-budget": {
		toolName: "get_token_budget",
		short:    "Run the get_token_budget tool against the warm daemon",
		groupID:  "memory",
		flags:    nil,
	},
	"get-tool-help": {
		toolName: "get_tool_help",
		short:    "Run the get_tool_help tool against the warm daemon",
		groupID:  "memory",
		flags: []verbFlag{
			{name: "tool-name", toolArg: "tool_name", kind: flagString, required: false, help: "Name of the tool to get help for"},
			{name: "topic", toolArg: "topic", kind: flagString, required: false, help: "Documentation topic name (alternative to tool_name): guardrails, dod, workflow:rename, workflow:delete, workflow:large-edit, workflow:security-sensitive-edit"},
		},
	},
	"get-type-hierarchy": {
		toolName: "get_type_hierarchy",
		short:    "Run the get_type_hierarchy tool against the warm daemon",
		groupID:  "navigation",
		flags: []verbFlag{
			{name: "path", toolArg: "path", kind: flagString, required: true, help: "File path"},
			{name: "line", toolArg: "line", kind: flagInt, required: true, help: "Line number (1-indexed, matches editor display)"},
			{name: "column", toolArg: "column", kind: flagInt, required: true, help: "Column number (1-indexed, matches editor display)"},
			{name: "direction", toolArg: "direction", kind: flagString, required: false, help: "subtypes, supertypes, or both (default: both)"},
		},
	},
	"go-to-definition": {
		toolName: "go_to_definition",
		short:    "Run the go_to_definition tool against the warm daemon",
		groupID:  "navigation",
		flags: []verbFlag{
			{name: "path", toolArg: "path", kind: flagString, required: true, help: "File path"},
			{name: "line", toolArg: "line", kind: flagInt, required: true, help: "Line number (1-indexed, matches editor display)"},
			{name: "column", toolArg: "column", kind: flagInt, required: true, help: "Column number (1-indexed, matches editor display)"},
		},
	},
	"index-semantic-graph": {
		toolName: "index_semantic_graph",
		short:    "Run the index_semantic_graph tool against the warm daemon",
		groupID:  "repomap",
		flags: []verbFlag{
			{name: "mode-arg", toolArg: "mode", kind: flagString, required: false, help: "auto, full, incremental, or refresh"},
			{name: "max-duration-ms", toolArg: "max_duration_ms", kind: flagInt, required: false, help: "per-call timeout in ms (default 120000)"},
			{name: "paths", toolArg: "paths", kind: flagStringSlice, required: false, help: "optional path filter (relative to workspace root)"},
		},
	},
	"insert-after-symbol": {
		toolName: "insert_after_symbol",
		short:    "Run the insert_after_symbol tool against the warm daemon",
		groupID:  "edit",
		flags: []verbFlag{
			{name: "path", toolArg: "path", kind: flagString, required: true, help: "File path"},
			{name: "symbol-name", toolArg: "symbol_name", kind: flagString, required: true, help: "Name of the symbol to insert after"},
			{name: "content", toolArg: "content", kind: flagString, required: true, help: "Content to insert"},
		},
	},
	"insert-before-symbol": {
		toolName: "insert_before_symbol",
		short:    "Run the insert_before_symbol tool against the warm daemon",
		groupID:  "edit",
		flags: []verbFlag{
			{name: "path", toolArg: "path", kind: flagString, required: true, help: "File path"},
			{name: "symbol-name", toolArg: "symbol_name", kind: flagString, required: true, help: "Name of the symbol to insert before"},
			{name: "content", toolArg: "content", kind: flagString, required: true, help: "Content to insert"},
		},
	},
	"list-directory": {
		toolName: "list_directory",
		short:    "Run the list_directory tool against the warm daemon",
		groupID:  "fileops",
		flags: []verbFlag{
			{name: "path", toolArg: "path", kind: flagString, required: true, help: "Directory path (relative to workspace root)"},
		},
	},
	"list-memories": {
		toolName: "list_memories",
		short:    "Run the list_memories tool against the warm daemon",
		groupID:  "memory",
		flags:    nil,
	},
	"onboard-project": {
		toolName: "onboard_project",
		short:    "Run the onboard_project tool against the warm daemon",
		groupID:  "memory",
		flags:    nil,
	},
	"prepare-for-new-conversation": {
		toolName: "prepare_for_new_conversation",
		short:    "Run the prepare_for_new_conversation tool against the warm daemon",
		groupID:  "memory",
		flags:    nil,
	},
	"read-file": {
		toolName: "read_file",
		short:    "Run the read_file tool against the warm daemon",
		groupID:  "fileops",
		flags: []verbFlag{
			{name: "path", toolArg: "path", kind: flagString, required: true, help: "File path to read (relative to workspace root)"},
			{name: "start-line", toolArg: "start_line", kind: flagInt, required: false, help: "Start line (1-indexed, optional)"},
			{name: "end-line", toolArg: "end_line", kind: flagInt, required: false, help: "End line (1-indexed, inclusive, optional)"},
		},
	},
	"read-memory": {
		toolName: "read_memory",
		short:    "Run the read_memory tool against the warm daemon",
		groupID:  "memory",
		flags:    nil,
	},
	"refresh-semantic-graph": {
		toolName: "refresh_semantic_graph",
		short:    "Run the refresh_semantic_graph tool against the warm daemon",
		groupID:  "repomap",
		flags: []verbFlag{
			{name: "paths", toolArg: "paths", kind: flagStringSlice, required: false, help: "strict-subset path filter (D-11): only requested paths are processed; remainder remain queued"},
			{name: "wait-for-lsp", toolArg: "wait_for_lsp", kind: flagBool, required: false, help: "block on LSP enrichment queue draining (cap = max_wait_ms)"},
			{name: "max-wait-ms", toolArg: "max_wait_ms", kind: flagInt, required: false, help: "foreground cap for wait_for_lsp polling in ms (default 3000)"},
		},
	},
	"rename-memory": {
		toolName: "rename_memory",
		short:    "Run the rename_memory tool against the warm daemon",
		groupID:  "memory",
		flags:    nil,
	},
	"rename-symbol": {
		toolName: "rename_symbol",
		short:    "Run the rename_symbol tool against the warm daemon",
		groupID:  "edit",
		flags: []verbFlag{
			{name: "path", toolArg: "path", kind: flagString, required: true, help: "File path where symbol is defined"},
			{name: "line", toolArg: "line", kind: flagInt, required: true, help: "Line number of symbol (1-indexed)"},
			{name: "column", toolArg: "column", kind: flagInt, required: true, help: "Column number of symbol (1-indexed)"},
			{name: "new-name", toolArg: "new_name", kind: flagString, required: true, help: "New name for the symbol"},
			{name: "receipts", toolArg: "receipts", kind: flagStringSlice, required: false, help: "Receipt IDs from prior find_references / analyze_blast_radius / get_context / get_repo_map / verify_edit calls. Required by guardrails (Phase 66 GUARD-03) for destructive operations on referenced or public-API symbols. Empty array when no receipts apply."},
		},
	},
	"replace-in-file": {
		toolName: "replace_in_file",
		short:    "Run the replace_in_file tool against the warm daemon",
		groupID:  "fileops",
		flags: []verbFlag{
			{name: "path", toolArg: "path", kind: flagString, required: true, help: "File path (relative to workspace root)"},
			{name: "pattern", toolArg: "pattern", kind: flagString, required: true, help: "Pattern to search for (literal or regex)"},
			{name: "replacement", toolArg: "replacement", kind: flagString, required: true, help: "Replacement string"},
			{name: "is-regex", toolArg: "is_regex", kind: flagBool, required: false, help: "Treat pattern as regex (default false)"},
			{name: "receipts", toolArg: "receipts", kind: flagStringSlice, required: false, help: "Receipt IDs from prior find_references / analyze_blast_radius / get_context / get_repo_map / verify_edit calls. Required by guardrails (Phase 66 GUARD-03) for destructive operations on referenced or public-API symbols. Empty array when no receipts apply."},
		},
	},
	"replace-symbol-body": {
		toolName: "replace_symbol_body",
		short:    "Run the replace_symbol_body tool against the warm daemon",
		groupID:  "edit",
		flags: []verbFlag{
			{name: "path", toolArg: "path", kind: flagString, required: true, help: "File path"},
			{name: "symbol-name", toolArg: "symbol_name", kind: flagString, required: true, help: "Name of the symbol whose body to replace"},
			{name: "new-body", toolArg: "new_body", kind: flagString, required: true, help: "New body content to replace with"},
			{name: "search-body", toolArg: "search_body", kind: flagString, required: false, help: "Optional: fuzzy-match this text within the symbol body before replacing. When absent, replaces the entire body."},
			{name: "receipts", toolArg: "receipts", kind: flagStringSlice, required: false, help: "Receipt IDs from prior find_references / analyze_blast_radius / get_context / get_repo_map / verify_edit calls. Required by guardrails (Phase 66 GUARD-03) for destructive operations on referenced or public-API symbols. Empty array when no receipts apply."},
		},
	},
	"safe-delete-symbol": {
		toolName: "safe_delete_symbol",
		short:    "Run the safe_delete_symbol tool against the warm daemon",
		groupID:  "edit",
		flags: []verbFlag{
			{name: "path", toolArg: "path", kind: flagString, required: true, help: "File path"},
			{name: "symbol-name", toolArg: "symbol_name", kind: flagString, required: true, help: "Name of the symbol to delete"},
			{name: "force", toolArg: "force", kind: flagBool, required: false, help: "Delete even if references exist (default: false)"},
			{name: "receipts", toolArg: "receipts", kind: flagStringSlice, required: false, help: "Receipt IDs from prior find_references / analyze_blast_radius / get_context / get_repo_map / verify_edit calls. Required by guardrails (Phase 66 GUARD-03) for destructive operations on referenced or public-API symbols. Empty array when no receipts apply."},
		},
	},
	"search-in-files": {
		toolName: "search_in_files",
		short:    "Run the search_in_files tool against the warm daemon",
		groupID:  "fileops",
		flags: []verbFlag{
			{name: "pattern", toolArg: "pattern", kind: flagString, required: true, help: "Regex pattern to search for"},
			{name: "include-glob", toolArg: "include_glob", kind: flagString, required: false, help: "Only search files matching this glob (optional)"},
			{name: "exclude-glob", toolArg: "exclude_glob", kind: flagString, required: false, help: "Skip files matching this glob (optional)"},
			{name: "context-lines", toolArg: "context_lines", kind: flagInt, required: false, help: "Number of context lines before/after match (optional)"},
			{name: "max-results", toolArg: "max_results", kind: flagInt, required: false, help: "Maximum number of results (default 100, optional)"},
		},
	},
	"search-memories": {
		toolName: "search_memories",
		short:    "Run the search_memories tool against the warm daemon",
		groupID:  "memory",
		flags:    nil,
	},
	"search-symbols": {
		toolName: "search_symbols",
		short:    "Run the search_symbols tool against the warm daemon",
		groupID:  "navigation",
		flags: []verbFlag{
			{name: "query", toolArg: "query", kind: flagString, required: true, help: "Symbol name or pattern to search"},
		},
	},
	"switch-mode": {
		toolName: "switch_mode",
		short:    "Run the switch_mode tool against the warm daemon",
		groupID:  "memory",
		flags:    nil,
	},
	"validate-graph-edge": {
		toolName: "validate_graph_edge",
		short:    "Run the validate_graph_edge tool against the warm daemon",
		groupID:  "repomap",
		flags: []verbFlag{
			{name: "from-json", toolArg: "from", kind: flagJSON, required: true, help: "source seed — symbol_id OR (file_path AND symbol_name)"},
			{name: "to-json", toolArg: "to", kind: flagJSON, required: true, help: "target seed — symbol_id OR (file_path AND symbol_name)"},
			{name: "edge-kind", toolArg: "edge_kind", kind: flagString, required: true, help: "closed surface enum: calls / references / implements / extends / has_type / uses_type / contains / defines / imports / data_flows / http_calls / async_calls / emits / listens_on / similar_to / semantically_related / handles / configures / writes / member_of / tests / file_changes_with / cross_imports / cross_calls / other"},
		},
	},
	"verify-edit": {
		toolName: "verify_edit",
		short:    "Run the verify_edit tool against the warm daemon",
		groupID:  "edit",
		flags: []verbFlag{
			{name: "path", toolArg: "path", kind: flagString, required: true, help: "File path to verify after editing"},
		},
	},
	"write-memory": {
		toolName: "write_memory",
		short:    "Run the write_memory tool against the warm daemon",
		groupID:  "memory",
		flags:    nil,
	},
}
