package main

import (
	"fmt"
	"go/format"
	"os"
	"strings"
)

// writeHeader writes the standard generation header to a string builder.
func writeHeader(b *strings.Builder, pkg string, version string) {
	fmt.Fprintf(b, "// Code generated by cmd/lspgen from LSP metaModel.json version %s. DO NOT EDIT.\n\n", version)
	fmt.Fprintf(b, "package %s\n\n", pkg)
}

// writeDoc writes a documentation comment block.
func writeDoc(b *strings.Builder, doc string) {
	if doc == "" {
		return
	}
	lines := strings.Split(doc, "\n")
	for _, line := range lines {
		line = strings.TrimRight(line, " \t\r")
		if line == "" {
			fmt.Fprintf(b, "//\n")
		} else {
			fmt.Fprintf(b, "// %s\n", line)
		}
	}
}

// writeFormatted formats Go source code and writes it to the given path.
func writeFormatted(path string, src string) error {
	formatted, err := format.Source([]byte(src))
	if err != nil {
		// Write unformatted for debugging
		if writeErr := os.WriteFile(path+".err", []byte(src), 0644); writeErr != nil {
			return fmt.Errorf("format error: %v (also failed to write debug file: %v)", err, writeErr)
		}
		return fmt.Errorf("format error in %s (debug written to %s.err): %v", path, path, err)
	}
	return os.WriteFile(path, formatted, 0644)
}
