package main

import (
	"fmt"
	"go/format"
	"sort"
	"strings"
)

// generatedHeader marks verbs_gen.go as machine-generated.
const generatedHeader = "// Code generated by helix-cligen; DO NOT EDIT."

// reservedRootFlags are the root command's persistent/local flags. A generated
// verb flag MUST NOT shadow one of these (cobra would panic "flag redefined",
// and a shadow could redirect the daemon/profile target — T-91-03). Kept in
// sync with internal/cli/root.go's rootCmd.Flags().
var reservedRootFlags = map[string]bool{
	"socket":                            true,
	"json":                              true,
	"profile":                           true,
	"config":                            true,
	"mode":                              true,
	"serve":                             true,
	"http-addr":                         true,
	"admin-addr":                        true,
	"version":                           true,
	"disable-lsp-subsystem":             true,
	"disable-structured-edit-subsystem": true,
	"disable-semantic-subsystem":        true,
}

// reservedSubcommands are the hand-written root subcommand names (the first
// token of each command's cobra Use string) plus the subcommands cobra adds
// automatically. A generated verb name MUST NOT collide with one of these:
// cobra's AddCommand panics ("...command ... is already registered") when two
// children share a name, which would crash the binary at init for ALL
// invocations. This is the subcommand-namespace analogue of reservedRootFlags
// (WR-03). Kept in sync with the addGrouped(...) calls in internal/cli/root.go
// and cobra's built-in help/completion commands.
var reservedSubcommands = map[string]bool{
	// Hand-written root subcommands (internal/cli/root.go).
	"setup":      true,
	"status":     true,
	"activate":   true,
	"deactivate": true,
	"nudge":      true,
	"update":     true,
	"upgrade":    true,
	// cobra auto-registers these on the root command.
	"help":       true,
	"completion": true,
}

// categoryToGroup maps a ToolProvider category (tp.Name()) to one of the 6
// capability cobra groups the generated verbs attach to on the root command.
// Unknown categories fall back to the memory/misc group so a newly-added tool
// is always grouped rather than dropped.
var categoryToGroup = map[string]string{
	"symbol-retrieval": groupNavigation,
	"symbols":          groupNavigation,
	"symbol-editing":   groupEdit,
	"file-ops":         groupFileops,
	"diagnostics":      groupDiagnostics,
	"repomap":          groupRepomap,
	"semantic":         groupRepomap,
	"memory":           groupMemory,
	"workflow":         groupMemory,
	"health":           groupMemory,
	"help":             groupMemory,
	"profile":          groupMemory,
}

// Group ID constants — must match the cobra.Group IDs registered in root.go.
const (
	groupNavigation  = "navigation"
	groupEdit        = "edit"
	groupFileops     = "fileops"
	groupDiagnostics = "diagnostics"
	groupRepomap     = "repomap"
	groupMemory      = "memory"
)

// flagKindFor maps a scanned field's goType discriminator to the verb.go
// flagKind identifier name emitted in the generated source.
func flagKindFor(goType string) string {
	switch goType {
	case "string":
		return "flagString"
	case "int":
		return "flagInt"
	case "bool":
		return "flagBool"
	case "[]string":
		return "flagStringSlice"
	default:
		return "flagJSON"
	}
}

// renderVerbsGen emits the committed internal/cli/verbs_gen.go populating
// verbSpecs with one entry per tool, sorted for deterministic gofmt-stable
// output. registryNames maps tool name -> ToolProvider category for grouping.
func renderVerbsGen(infos []*argInfo, registryNames map[string]string) (string, error) {
	sorted := append([]*argInfo(nil), infos...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].toolName < sorted[j].toolName })

	var b strings.Builder
	b.WriteString(generatedHeader + "\n")
	b.WriteString("// Regenerate with: go run ./cmd/helix-cligen\n\n")
	b.WriteString("package cli\n\n")
	b.WriteString("// verbSpecs is the generated verb->tool catalog: one entry per callable\n")
	b.WriteString("// tool in the live registry, flattened onto the root command grouped by\n")
	b.WriteString("// capability. Tools registered via the dynamic map[string]any handler\n")
	b.WriteString("// (AddSkillTool) carry no derivable flags and appear with an empty flag set.\n")
	b.WriteString("var verbSpecs = map[string]verbSpec{\n")

	for _, info := range sorted {
		verb := kebab(info.toolName)
		// WR-03: a generated verb name must not collide with a hand-written (or
		// cobra-auto) root subcommand, else rootCmd.AddCommand panics at init and
		// crashes the binary for ALL invocations. Fail generation loudly so the
		// collision is caught at generate/CI time rather than at the user's CLI.
		if reservedSubcommands[verb] {
			return "", fmt.Errorf(
				"verb %q (from tool %q) collides with a reserved root subcommand; "+
					"rename the tool or add a verb-name override (see reservedSubcommands)",
				verb, info.toolName,
			)
		}
		group := categoryToGroup[registryNames[info.toolName]]
		if group == "" {
			group = groupMemory
		}
		b.WriteString(fmt.Sprintf("\t%q: {\n", verb))
		b.WriteString(fmt.Sprintf("\t\ttoolName: %q,\n", info.toolName))
		b.WriteString(fmt.Sprintf("\t\tshort:    %q,\n", shortFor(info.toolName)))
		b.WriteString(fmt.Sprintf("\t\tgroupID:  %q,\n", group))
		if len(info.fields) == 0 {
			b.WriteString("\t\tflags:    nil,\n")
		} else {
			b.WriteString("\t\tflags: []verbFlag{\n")
			for _, f := range info.fields {
				flagName, kind := flagNameAndKind(f)
				b.WriteString(fmt.Sprintf(
					"\t\t\t{name: %q, toolArg: %q, kind: %s, required: %t, help: %q},\n",
					flagName, f.jsonKey, kind, f.required, f.help,
				))
			}
			b.WriteString("\t\t},\n")
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("gofmt generated source: %w", err)
	}
	return string(formatted), nil
}

// flagNameAndKind derives the kebab flag name and the verb.go flagKind for a
// field, applying the JSON-flag -json suffix and the reserved-root-flag rename.
func flagNameAndKind(f argField) (name, kind string) {
	kind = flagKindFor(f.goType)
	name = kebab(f.jsonKey)
	if kind == "flagJSON" {
		name = name + "-json"
	}
	// Never shadow a reserved root persistent flag: suffix deterministically.
	if reservedRootFlags[name] {
		name = name + "-arg"
	}
	return name, kind
}

// shortFor produces a stable one-line help for a verb. The authoritative
// description lives in the MCP ToolDef; here we emit a deterministic placeholder
// derived from the tool name so the generated file is self-contained and stable.
func shortFor(toolName string) string {
	return "Run the " + toolName + " tool against the warm daemon"
}

// kebab converts a snake_case identifier to kebab-case.
func kebab(s string) string {
	return strings.ReplaceAll(s, "_", "-")
}
