package main

import (
	"go/parser"
	"go/token"
	"strings"
	"testing"
)

func sampleInfos() []*argInfo {
	return []*argInfo{
		{toolName: "go_to_definition", fields: []argField{
			{jsonKey: "path", required: true, help: "File path", goType: "string"},
			{jsonKey: "line", required: true, help: "Line", goType: "int"},
		}},
		{toolName: "search_in_files", fields: []argField{
			{jsonKey: "pattern", required: true, help: "Regex", goType: "string"},
			{jsonKey: "max_results", required: false, help: "Max", goType: "int"},
		}},
	}
}

func sampleRegistry() map[string]string {
	return map[string]string{
		"go_to_definition": "symbol-retrieval",
		"search_in_files":  "file-ops",
	}
}

// TestRender_Deterministic asserts repeated renders are byte-identical.
func TestRender_Deterministic(t *testing.T) {
	a, err := renderVerbsGen(sampleInfos(), sampleRegistry())
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	b, err := renderVerbsGen(sampleInfos(), sampleRegistry())
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	if a != b {
		t.Fatalf("render not deterministic across calls")
	}
}

// TestRender_HeaderAndValidGo asserts the generated-code header and that the
// output parses as valid Go.
func TestRender_HeaderAndValidGo(t *testing.T) {
	out, err := renderVerbsGen(sampleInfos(), sampleRegistry())
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	if !strings.HasPrefix(out, "// Code generated by helix-cligen; DO NOT EDIT.") {
		t.Errorf("missing generated-code header; got start: %q", out[:min(60, len(out))])
	}
	if _, err := parser.ParseFile(token.NewFileSet(), "verbs_gen.go", out, parser.AllErrors); err != nil {
		t.Errorf("rendered output does not parse as Go: %v", err)
	}
}

// TestRender_KebabFlagSnakeToolArg asserts a snake_case json key renders a kebab
// flag name with the snake_case toolArg preserved.
func TestRender_KebabFlagSnakeToolArg(t *testing.T) {
	out, err := renderVerbsGen(sampleInfos(), sampleRegistry())
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	if !strings.Contains(out, `name: "max-results"`) {
		t.Errorf("expected kebab flag name max-results in output")
	}
	if !strings.Contains(out, `toolArg: "max_results"`) {
		t.Errorf("expected snake toolArg max_results in output")
	}
}

// TestRender_KindMapping asserts each goType maps to the right flagKind.
func TestRender_KindMapping(t *testing.T) {
	infos := []*argInfo{
		{toolName: "kindtool", fields: []argField{
			{jsonKey: "s", required: true, help: "s", goType: "string"},
			{jsonKey: "i", required: true, help: "i", goType: "int"},
			{jsonKey: "b", required: false, help: "b", goType: "bool"},
			{jsonKey: "ss", required: false, help: "ss", goType: "[]string"},
			{jsonKey: "receipts", required: false, help: "r", goType: ""},
		}},
	}
	reg := map[string]string{"kindtool": "file-ops"}
	out, err := renderVerbsGen(infos, reg)
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	for _, want := range []string{
		"kind: flagString",
		"kind: flagInt",
		"kind: flagBool",
		"kind: flagStringSlice",
		"kind: flagJSON",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("expected %q in rendered output for kind mapping", want)
		}
	}
	// The opaque (JSON) flag gets a -json suffix on the kebab name.
	if !strings.Contains(out, `name: "receipts-json"`) {
		t.Errorf("expected receipts-json flag name for opaque type")
	}
}

// TestRender_ReservedFlagDenylist asserts a field whose kebab name collides with
// a reserved root persistent flag is renamed deterministically.
func TestRender_ReservedFlagDenylist(t *testing.T) {
	infos := []*argInfo{
		{toolName: "conflicttool", fields: []argField{
			{jsonKey: "profile", required: true, help: "p", goType: "string"},
			{jsonKey: "socket", required: false, help: "s", goType: "string"},
		}},
	}
	reg := map[string]string{"conflicttool": "file-ops"}
	out, err := renderVerbsGen(infos, reg)
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	// Must NOT emit a bare --profile or --socket verb flag (would shadow root).
	if strings.Contains(out, `name: "profile"`) {
		t.Errorf("verb flag must not shadow reserved root flag --profile")
	}
	if strings.Contains(out, `name: "socket"`) {
		t.Errorf("verb flag must not shadow reserved root flag --socket")
	}
	// The toolArg must still carry the real key so the daemon receives it.
	if !strings.Contains(out, `toolArg: "profile"`) {
		t.Errorf("renamed flag must preserve toolArg profile")
	}
}

// TestRender_ReservedSubcommandFailsGeneration is the WR-03 regression: a
// generated verb name that collides with a hand-written root subcommand must
// hard-fail generation, since rootCmd.AddCommand would panic at init.
func TestRender_ReservedSubcommandFailsGeneration(t *testing.T) {
	infos := []*argInfo{
		{toolName: "status", fields: []argField{
			{jsonKey: "path", required: true, help: "p", goType: "string"},
		}},
	}
	reg := map[string]string{"status": "file-ops"}
	_, err := renderVerbsGen(infos, reg)
	if err == nil {
		t.Fatalf("expected reserved-subcommand error, got nil")
	}
	if !strings.Contains(err.Error(), "reserved root subcommand") {
		t.Errorf("expected reserved-subcommand error, got: %v", err)
	}
}

// TestRender_ReservedSubcommandSetMatchesRoot keeps the WR-03 denylist honest:
// every hand-written root subcommand name must be present in reservedSubcommands
// so a future tool named after one of them is caught at generate time.
func TestRender_ReservedSubcommandSetMatchesRoot(t *testing.T) {
	for _, name := range []string{
		"setup", "status", "activate", "deactivate", "nudge", "update", "upgrade",
	} {
		if !reservedSubcommands[name] {
			t.Errorf("hand-written root subcommand %q missing from reservedSubcommands", name)
		}
	}
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
