package main

import (
	"fmt"
	"strings"

	"github.com/agenthands/helix/internal/cli"
	"github.com/agenthands/helix/internal/skill"
)

// renderReference renders the full per-verb reference.md from the live registry.
// It is deterministic: the per-verb args/synopsis are sourced from sorted,
// fresh-copy accessors (cli.VerbSpecsForDocs for args, the ToolProviders walk for
// the synopsis prose) and emitted in verb-sorted order, so two calls produce
// byte-identical output. Args come from VerbSpecsForDocs (NOT tool.InputSchema,
// which is not a field on mcp.ToolDef — see 97-RESEARCH.md Pitfall 1).
func renderReference() string {
	// 1. Synopsis prose per kebab verb, from the ToolProvider walk (tool.Description).
	//    Keyed off the kebab name (ReplaceAll(tool.Name,"_","-")), same mechanical
	//    mapping docgen uses. Pipe-escaped (Security V12, markup injection).
	synopsis := make(map[string]string)
	for _, tp := range skill.ToolProviders() {
		for _, tool := range tp.Tools() {
			verb := strings.ReplaceAll(tool.Name, "_", "-")
			desc := firstSentence(tool.Description)
			desc = strings.ReplaceAll(desc, "|", "\\|")
			if _, seen := synopsis[verb]; !seen {
				synopsis[verb] = desc
			}
		}
	}

	var sb strings.Builder
	sb.WriteString("<!-- Code generated by helix-refgen; DO NOT EDIT. Regenerate with: go run ./cmd/helix-refgen -->\n\n")
	sb.WriteString("# helix verb reference\n\n")
	sb.WriteString("On-demand per-verb reference for the frozen `helix` CLI verbs. Each section ")
	sb.WriteString("carries a synopsis, the flags it accepts, the output shape, a worked example, ")
	sb.WriteString("and a use-this-not-that pointer toward the verb (away from grep/sed/cat).\n\n")

	// 2. One section per verb, sorted by kebab key (VerbSpecsForDocs is sorted).
	for _, d := range cli.VerbSpecsForDocs() {
		sb.WriteString(renderVerb(d, synopsis[d.Verb]))
	}
	// Normalize to exactly one trailing newline (each section ends in "\n\n").
	return strings.TrimRight(sb.String(), "\n") + "\n"
}

// renderVerb renders a single verb's section deterministically.
func renderVerb(d cli.VerbDoc, syn string) string {
	var sb strings.Builder
	sb.WriteString("## `helix ")
	sb.WriteString(d.Verb)
	sb.WriteString("`\n\n")

	// Synopsis.
	if strings.TrimSpace(syn) == "" {
		syn = d.Short
	}
	sb.WriteString("**Synopsis:** ")
	sb.WriteString(strings.TrimSpace(syn))
	sb.WriteString("\n\n")

	// Args list (from VerbSpecsForDocs flags; deterministic, in catalog order).
	sb.WriteString("**Args:**\n\n")
	if len(d.Flags) == 0 {
		sb.WriteString("- (none)\n\n")
	} else {
		for _, f := range d.Flags {
			req := "optional"
			if f.Required {
				req = "required"
			}
			help := strings.ReplaceAll(f.Help, "|", "\\|")
			sb.WriteString(fmt.Sprintf("- `--%s` (%s, %s) — %s\n", f.Name, f.Kind, req, strings.TrimSpace(help)))
		}
		sb.WriteString("\n")
	}

	// Output shape (per group).
	sb.WriteString("**Output:** ")
	sb.WriteString(outputShape(d.GroupID))
	sb.WriteString("\n\n")

	// Worked example.
	sb.WriteString("**Example:**\n\n```\n")
	sb.WriteString(workedExample(d))
	sb.WriteString("\n```\n\n")

	// Use-this-not-that.
	sb.WriteString("**Use this, not that:** ")
	sb.WriteString(useThisNotThat(d.GroupID, d.Verb))
	sb.WriteString("\n\n")

	return sb.String()
}

// firstSentence truncates a description at the first sentence boundary (mirrors
// the docgen table truncation), keeping the synopsis terse and deterministic.
func firstSentence(desc string) string {
	desc = strings.TrimSpace(desc)
	if idx := strings.Index(desc, ". "); idx > 0 && idx < 160 {
		return desc[:idx+1]
	}
	return desc
}

// workedExample builds a generic, deterministic `helix <verb> ...` invocation from
// the verb's required flags (falling back to all flags when none are required, or
// the bare verb when it has none). Values are placeholder tokens keyed on the flag
// name/kind so the example is illustrative without being hand-authored.
func workedExample(d cli.VerbDoc) string {
	var parts []string
	parts = append(parts, "helix", d.Verb)
	used := flagsForExample(d.Flags)
	for _, f := range used {
		parts = append(parts, fmt.Sprintf("--%s=%s", f.Name, placeholder(f)))
	}
	return strings.Join(parts, " ")
}

// flagsForExample returns the required flags, or (when none are required) all
// flags, in catalog order. Deterministic.
func flagsForExample(flags []cli.FlagDoc) []cli.FlagDoc {
	var req []cli.FlagDoc
	for _, f := range flags {
		if f.Required {
			req = append(req, f)
		}
	}
	if len(req) > 0 {
		return req
	}
	return flags
}

// placeholder returns a deterministic example value token for a flag, keyed on its
// kind and name.
func placeholder(f cli.FlagDoc) string {
	switch f.Kind {
	case "int":
		switch f.Name {
		case "line":
			return "42"
		case "column":
			return "8"
		default:
			return "1"
		}
	case "bool":
		return "true"
	case "string-slice":
		return "a,b"
	case "json":
		return "'[]'"
	default:
		switch f.Name {
		case "path":
			return "internal/foo/bar.go"
		case "query":
			return "Foo"
		case "name":
			return "FooBar"
		default:
			return "<" + f.Name + ">"
		}
	}
}

// outputShape returns the deterministic per-group output-shape note.
func outputShape(group string) string {
	switch group {
	case "navigation":
		return "terse `relpath:line:col<TAB>payload`, one locus per line, sorted and deduped (1-based); navigation verbs append a snippet line."
	case "edit":
		return "an applied-edit summary (files touched, fuzzy strategy when used); a failing edit prints a typed `kind: msg` to stderr."
	case "fileops":
		return "file content or a `relpath`-anchored listing; structured per-line output piped plain (no ANSI)."
	case "diagnostics":
		return "`relpath:line:col<TAB>severity<TAB>message` diagnostics, or the available code actions / formatted output."
	case "memory":
		return "the memory body or a ranked FTS5 search result set, one entry per line."
	case "repomap":
		return "a ranked, token-budgeted structural overview or context bundle (relpath-anchored)."
	default:
		return "terse, `relpath:line:col`-anchored output; a failing verb prints a typed `kind: msg` to stderr and exits non-zero."
	}
}

// useThisNotThat returns the deterministic per-group "use this verb, not the
// standard tool" pointer.
func useThisNotThat(group, verb string) string {
	cmd := "`helix " + verb + "`"
	switch group {
	case "navigation":
		return "Use " + cmd + " for symbol-level questions instead of `grep`/`grep -r` — it resolves real definitions and references via the LSP, not string matches."
	case "edit":
		return "Use " + cmd + " for symbol-aware edits instead of `sed`/`sed -i` — it edits by AST/symbol, tolerant of LLM output drift."
	case "fileops":
		return "Use " + cmd + " instead of `cat`/`find`/`grep -r` — terse, `relpath`-anchored output built for agents."
	case "diagnostics":
		return "Use " + cmd + " instead of parsing raw build output — it surfaces structured, locus-anchored diagnostics and quick-fixes."
	case "memory":
		return "Use " + cmd + " for durable project/session memory instead of ad-hoc scratch notes."
	case "repomap":
		return "Use " + cmd + " for a ranked structural overview instead of reading many files by hand."
	default:
		return "Use " + cmd + " instead of falling back to grep/sed/cat for this task."
	}
}
