package main

import (
	"fmt"
	"strings"

	"github.com/agenthands/helix/internal/cli"
	"github.com/agenthands/helix/internal/skill"
)

// renderReference renders the full per-verb reference.md from the live registry.
// It is deterministic: the per-verb args/synopsis are sourced from sorted,
// fresh-copy accessors (cli.VerbSpecsForDocs for args, the ToolProviders walk for
// the synopsis prose) and emitted in verb-sorted order, so two calls produce
// byte-identical output. Args come from VerbSpecsForDocs (NOT tool.InputSchema,
// which is not a field on mcp.ToolDef — see 97-RESEARCH.md Pitfall 1).
func renderReference() string {
	// 1. Synopsis prose per kebab verb, from the ToolProvider walk (tool.Description).
	//    Keyed off the kebab name (ReplaceAll(tool.Name,"_","-")), same mechanical
	//    mapping docgen uses. Pipe-escaped (Security V12, markup injection).
	synopsis := make(map[string]string)
	for _, tp := range skill.ToolProviders() {
		for _, tool := range tp.Tools() {
			verb := strings.ReplaceAll(tool.Name, "_", "-")
			desc := firstSentence(tool.Description)
			desc = strings.ReplaceAll(desc, "|", "\\|")
			if _, seen := synopsis[verb]; !seen {
				synopsis[verb] = desc
			}
		}
	}

	var sb strings.Builder
	sb.WriteString("<!-- Code generated by helix-refgen; DO NOT EDIT. Regenerate with: go run ./cmd/helix-refgen -->\n\n")
	sb.WriteString("# helix verb reference\n\n")
	sb.WriteString("On-demand per-verb reference for the frozen `helix` CLI verbs. Each section ")
	sb.WriteString("carries a synopsis, the flags it accepts, the output shape, a worked example, ")
	sb.WriteString("and a use-this-not-that pointer toward the verb (away from grep/sed/cat).\n\n")

	// 2. One section per verb, sorted by kebab key (VerbSpecsForDocs is sorted).
	for _, d := range cli.VerbSpecsForDocs() {
		sb.WriteString(renderVerb(d, synopsis[d.Verb]))
	}
	// Normalize to exactly one trailing newline (each section ends in "\n\n").
	return strings.TrimRight(sb.String(), "\n") + "\n"
}

// renderVerb renders a single verb's section deterministically.
func renderVerb(d cli.VerbDoc, syn string) string {
	var sb strings.Builder
	sb.WriteString("## `helix ")
	sb.WriteString(d.Verb)
	sb.WriteString("`\n\n")

	// Synopsis.
	if strings.TrimSpace(syn) == "" {
		syn = d.Short
	}
	sb.WriteString("**Synopsis:** ")
	sb.WriteString(strings.TrimSpace(syn))
	sb.WriteString("\n\n")

	// Args list (from VerbSpecsForDocs flags; deterministic, in catalog order).
	sb.WriteString("**Args:**\n\n")
	if len(d.Flags) == 0 {
		sb.WriteString("- (none)\n\n")
	} else {
		for _, f := range d.Flags {
			req := "optional"
			if f.Required {
				req = "required"
			}
			help := strings.ReplaceAll(f.Help, "|", "\\|")
			sb.WriteString(fmt.Sprintf("- `--%s` (%s, %s) — %s\n", f.Name, f.Kind, req, strings.TrimSpace(help)))
		}
		sb.WriteString("\n")
	}

	// Output shape (per-verb override, else per-group default).
	sb.WriteString("**Output:** ")
	sb.WriteString(outputShape(d.Verb, d.GroupID))
	sb.WriteString("\n\n")

	// Worked example.
	sb.WriteString("**Example:**\n\n```\n")
	sb.WriteString(workedExample(d))
	sb.WriteString("\n```\n\n")

	// Use-this-not-that (per-verb override, else per-group default).
	sb.WriteString("**Use this, not that:** ")
	sb.WriteString(useThisNotThat(d.Verb, d.GroupID))
	sb.WriteString("\n\n")

	return sb.String()
}

// sentenceAbbreviations are common abbreviations that end in a period followed by
// a space. A naive "first `. ` is a sentence boundary" split would truncate the
// synopsis mid-clause at one of these, so firstSentence skips past them.
var sentenceAbbreviations = []string{"e.g.", "i.e.", "vs.", "etc.", "cf.", "no.", "al.", "ca."}

// firstSentence truncates a description at the first sentence boundary (mirrors
// the docgen table truncation), keeping the synopsis terse and deterministic.
// It does NOT treat a ". " that closes a known abbreviation (e.g. "e.g. ",
// "i.e. ") as a sentence boundary — it scans for the next real boundary instead —
// so the synopsis is not silently truncated mid-clause (WR-01).
func firstSentence(desc string) string {
	desc = strings.TrimSpace(desc)
	start := 0
	for {
		rel := strings.Index(desc[start:], ". ")
		if rel < 0 {
			return desc
		}
		idx := start + rel
		if idx <= 0 || idx >= 160 {
			return desc
		}
		if !endsWithAbbreviation(desc[:idx+1]) {
			return desc[:idx+1]
		}
		// The boundary closed an abbreviation; keep scanning past it.
		start = idx + 2
	}
}

// endsWithAbbreviation reports whether head (which ends in ".") closes a known
// abbreviation. The comparison is case-insensitive on the trailing token so
// "E.g." and "e.g." are both caught.
func endsWithAbbreviation(head string) bool {
	lower := strings.ToLower(head)
	for _, abbr := range sentenceAbbreviations {
		if strings.HasSuffix(lower, abbr) {
			return true
		}
	}
	return false
}

// workedExample builds a generic, deterministic `helix <verb> ...` invocation from
// the verb's required flags (falling back to all flags when none are required, or
// the bare verb when it has none). Values are placeholder tokens keyed on the flag
// name/kind so the example is illustrative without being hand-authored.
func workedExample(d cli.VerbDoc) string {
	var parts []string
	parts = append(parts, "helix", d.Verb)
	used := flagsForExample(d.Flags)
	for _, f := range used {
		parts = append(parts, fmt.Sprintf("--%s=%s", f.Name, placeholder(f)))
	}
	return strings.Join(parts, " ")
}

// flagsForExample returns the required flags, or (when none are required) all
// flags, in catalog order. Deterministic.
func flagsForExample(flags []cli.FlagDoc) []cli.FlagDoc {
	var req []cli.FlagDoc
	for _, f := range flags {
		if f.Required {
			req = append(req, f)
		}
	}
	if len(req) > 0 {
		return req
	}
	return flags
}

// placeholder returns a deterministic example value token for a flag, keyed on its
// kind and name.
func placeholder(f cli.FlagDoc) string {
	switch f.Kind {
	case "int":
		switch f.Name {
		case "line":
			return "42"
		case "column":
			return "8"
		default:
			return "1"
		}
	case "bool":
		return "true"
	case "string-slice":
		return "a,b"
	case "json":
		return "'[]'"
	default:
		switch f.Name {
		case "path":
			return "internal/foo/bar.go"
		case "query":
			return "Foo"
		case "name":
			return "FooBar"
		default:
			return "<" + f.Name + ">"
		}
	}
}

// outputShapeOverrides corrects the Output prose for verbs whose collapsed
// GroupID ("memory", from cligen's categoryToGroup folding profile/workflow/
// health/help/memory-mutate into groupMemory) would otherwise inherit the
// memory-query default. Keyed on the kebab verb; consulted by KEYED lookup
// (never ranged) so renderReference stays byte-deterministic.
var outputShapeOverrides = map[string]string{
	"write-memory":                 "a confirmation that the named memory was written (durable markdown + FTS5 index updated).",
	"edit-memory":                  "a confirmation that the named memory's body was updated in place.",
	"delete-memory":                "a confirmation that the named memory was removed (markdown + FTS5 index).",
	"rename-memory":                "a confirmation that the memory was renamed (old name freed, new name indexed).",
	"switch-mode":                  "the active profile mode after the switch and the tool surface it now gates.",
	"get-token-budget":             "the per-tool token budget for the active profile/mode.",
	"onboard-project":              "a workspace onboarding summary (detected languages, entry points, suggested first memories).",
	"prepare-for-new-conversation": "a session-handoff summary seeding the next conversation with the current working context.",
	"get-health":                   "per-workspace language-server status, capabilities, and indexing progress.",
	"get-tool-help":                "comprehensive on-demand documentation for the named tool (args, output, usage).",
}

// useThisNotThatOverrides corrects the "use this, not that" prose for the same
// 10 verbs (see outputShapeOverrides). Values are full sentences (the verb
// reference is built inline via `helix <verb>`); keyed lookup only.
var useThisNotThatOverrides = map[string]string{
	"write-memory":                 "Use `helix write-memory` to persist a durable project/session note instead of leaving it in chat scratch — it is indexed for later recall.",
	"edit-memory":                  "Use `helix edit-memory` to update a stored memory's body instead of re-writing it by hand — the FTS5 index stays in sync.",
	"delete-memory":                "Use `helix delete-memory` to remove a stored memory instead of editing the markdown file directly — the index is updated too.",
	"rename-memory":                "Use `helix rename-memory` to rename a stored memory instead of moving the file by hand — references and the index follow.",
	"switch-mode":                  "Use `helix switch-mode` to change the active profile mode instead of editing config by hand — it re-gates the tool surface atomically.",
	"get-token-budget":             "Use `helix get-token-budget` to read the active profile's per-tool token budget instead of guessing limits.",
	"onboard-project":              "Use `helix onboard-project` to bootstrap workspace context instead of manually exploring the tree — it detects languages and entry points for you.",
	"prepare-for-new-conversation": "Use `helix prepare-for-new-conversation` to capture a session handoff instead of re-deriving context next time.",
	"get-health":                   "Use `helix get-health` to inspect language-server status and indexing progress instead of guessing whether the daemon is warm.",
	"get-tool-help":                "Use `helix get-tool-help` for authoritative on-demand tool docs instead of guessing a verb's args or output shape.",
}

// outputShape returns the per-verb Output override when one exists, else the
// per-group default. Keyed lookup keeps renderReference deterministic.
func outputShape(verb, group string) string {
	if s, ok := outputShapeOverrides[verb]; ok {
		return s
	}
	return groupOutputDefault(group)
}

// groupOutputDefault returns the deterministic per-group output-shape note.
func groupOutputDefault(group string) string {
	switch group {
	case "navigation":
		return "terse `relpath:line:col<TAB>payload`, one locus per line, sorted and deduped (1-based); navigation verbs append a snippet line."
	case "edit":
		return "an applied-edit summary (files touched, fuzzy strategy when used); a failing edit prints a typed `kind: msg` to stderr."
	case "fileops":
		return "file content or a `relpath`-anchored listing; structured per-line output piped plain (no ANSI)."
	case "diagnostics":
		return "`relpath:line:col<TAB>severity<TAB>message` diagnostics, or the available code actions / formatted output."
	case "memory":
		return "the memory body or a ranked FTS5 search result set, one entry per line."
	case "repomap":
		return "a ranked, token-budgeted structural overview or context bundle (relpath-anchored)."
	default:
		return "terse, `relpath:line:col`-anchored output; a failing verb prints a typed `kind: msg` to stderr and exits non-zero."
	}
}

// useThisNotThat returns the per-verb "use this, not that" override when one
// exists, else the per-group default. Keyed lookup keeps render deterministic.
func useThisNotThat(verb, group string) string {
	if s, ok := useThisNotThatOverrides[verb]; ok {
		return s
	}
	return groupUseDefault(group, verb)
}

// groupUseDefault returns the deterministic per-group "use this verb, not the
// standard tool" pointer.
func groupUseDefault(group, verb string) string {
	cmd := "`helix " + verb + "`"
	switch group {
	case "navigation":
		return "Use " + cmd + " for symbol-level questions instead of `grep`/`grep -r` — it resolves real definitions and references via the LSP, not string matches."
	case "edit":
		return "Use " + cmd + " for symbol-aware edits instead of `sed`/`sed -i` — it edits by AST/symbol, tolerant of LLM output drift."
	case "fileops":
		return "Use " + cmd + " instead of `cat`/`find`/`grep -r` — terse, `relpath`-anchored output built for agents."
	case "diagnostics":
		return "Use " + cmd + " instead of parsing raw build output — it surfaces structured, locus-anchored diagnostics and quick-fixes."
	case "memory":
		return "Use " + cmd + " for durable project/session memory instead of ad-hoc scratch notes."
	case "repomap":
		return "Use " + cmd + " for a ranked structural overview instead of reading many files by hand."
	default:
		return "Use " + cmd + " instead of falling back to grep/sed/cat for this task."
	}
}
