package upgrade

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"os"
	"strings"

	"github.com/sigstore/sigstore-go/pkg/bundle"
	"github.com/sigstore/sigstore-go/pkg/root"
	"github.com/sigstore/sigstore-go/pkg/verify"
)

// The error string "signature verification FAILED" is the SINGLE message
// returned by VerifyArchive at every failure site (read-archive,
// read-bundle, parse-trust-root, parse-bundle, build-verifier, identity
// mismatch, signature/tlog/timestamp failure, missing-file). The wording
// is deliberately identical at all branches so an attacker probing the
// failure modes cannot distinguish "tampered bundle" from "wrong trust
// root" from "wrong identity" by inspecting the error text. See
// 52-RESEARCH.md Pitfall 4 (preserved across the Phase 58 D-02 minisign →
// sigstore-go cutover).
//
// The literal is repeated at each return site (rather than centralized in
// a sentinel) so a `grep -c 'signature verification FAILED'` gate can
// confirm coverage at every failure branch. Each return site carries an
// inline `// canonical: signature verification FAILED — see Pitfall 4.`
// comment so a comment-stripped grep counts only real failure branches.
//
// The Rekor-unreachable branch is the SOLE exception: it returns a
// fmt.Errorf with the canonical literal as a prefix AND the user-friendly
// "Rekor transparency-log verification requires network access" wording
// from D-04. The expanded message lets the user distinguish "your network
// is offline" from "your archive is tampered" — both are upgrade refusals
// but different actions are required to recover.

// pinnedOIDCIssuer is the GitHub Actions OIDC issuer URL. Phase 58 D-02 /
// R-2 — every Helix release cert chain MUST anchor to this issuer.
const pinnedOIDCIssuer = "https://token.actions.githubusercontent.com"

// pinnedSANRegexLiteral pins the certificate Subject Alternative Name to
// the agenthands/helix release.yml workflow on a semver tag. The optional
// -rc/-beta/-alpha pre-release suffix matches goreleaser's
// `prerelease: auto` behavior in `.goreleaser.yaml:94` (per
// 58-RESEARCH.md line 139/440).
//
// IN-04 tightening: the version segment is `\d+\.\d+\.\d+` rather than
// `[\d.]+` so ill-formed tags like `v1.2.3.4` or `v..1` are rejected at
// the verifier layer even if some upstream component minted a cert for
// such a tag. Goreleaser's `prerelease: auto` already constrains real
// release tags to canonical semver, but defense-in-depth pinning at the
// verifier mirrors that constraint.
//
// Final-tag-only narrowing (e.g., `v\d+\.\d+\.\d+$`) would reject any
// signed pre-release self-upgrade — DO NOT drop the optional pre-release
// suffix.
const pinnedSANRegexLiteral = `^https://github\.com/agenthands/helix/\.github/workflows/release\.yml@refs/tags/v\d+\.\d+\.\d+(-rc\d+|-beta\d+|-alpha\d+)?$`

// testTrustedRootOverride lets tests substitute a non-production sigstore
// TUF trust root JSON (typically generated by VirtualSigstore in
// internal/upgrade/testdata/generate_fixtures.go) without touching the
// embedded trustedRootJSON. Tests set this in setup, defer-clear it, and
// call VerifyArchive normally. Production callers leave it nil so the
// embedded trust root is used.
//
// Package-private to prevent external callers from disabling identity
// pinning at runtime.
var testTrustedRootOverride []byte

// testRekorURLOverride lets tests inject a deliberately-unreachable Rekor
// URL (typically a closed httptest.Server's host:port) into the network
// classifier so the user-friendly "Rekor unreachable" branch can be
// exercised in unit tests. Production callers leave it empty.
var testRekorURLOverride string

// currentTrustedRoot returns the active trust root JSON — the test
// override when set, otherwise the embedded production trust root.
func currentTrustedRoot() []byte {
	if testTrustedRootOverride != nil {
		return testTrustedRootOverride
	}
	return trustedRootJSON
}

// VerifyArchive verifies that bundlePath is a valid sigstore cosign-keyless
// bundle for archivePath under the embedded trusted root (or the test
// override during tests). Returns nil iff:
//
//  1. The trust root parses;
//  2. The bundle parses;
//  3. The bundle's certificate chain anchors to the trust root's Fulcio
//     CA chain;
//  4. The DSSE/messageSignature verifies over the archive bytes;
//  5. The Rekor transparency-log entry verifies (signed entry timestamp
//     SET checks against the trust root's Rekor public key);
//  6. The signed timestamp from the TSA verifies;
//  7. The certificate's SAN matches pinnedSANRegex AND its OIDC issuer
//     extension equals pinnedOIDCIssuer.
//
// On any failure VerifyArchive returns the SAME canonical error message
// ("signature verification FAILED"). This is intentional per RESEARCH.md
// Pitfall 4: an attacker who can probe the failure mode (by sending
// tampered vs. wrong-identity bundles) must not be able to distinguish
// them by error text. The single-message rule means the upgrade
// subcommand always prints the same string; downstream logging never
// branches on the verify outcome.
//
// The Rekor-unreachable branch is the SOLE exception: it wraps the
// canonical literal with the additional user-friendly wording from D-04.
// See the package-level Pitfall-4 invariant comment block for the
// rationale (Rekor unreachability is operationally distinct from
// signature failure — different recovery action — and the threat model
// allows the disclosure).
func VerifyArchive(archivePath, bundlePath string) error {
	archiveBytes, err := os.ReadFile(archivePath)
	if err != nil {
		// canonical: signature verification FAILED — see Pitfall 4.
		return errors.New("signature verification FAILED")
	}
	bundleBytes, err := os.ReadFile(bundlePath)
	if err != nil {
		// canonical: signature verification FAILED — see Pitfall 4.
		return errors.New("signature verification FAILED")
	}

	tr, err := root.NewTrustedRootFromJSON(currentTrustedRoot())
	if err != nil {
		// canonical: signature verification FAILED — see Pitfall 4.
		return errors.New("signature verification FAILED")
	}

	b := &bundle.Bundle{}
	if err := b.UnmarshalJSON(bundleBytes); err != nil {
		// canonical: signature verification FAILED — see Pitfall 4.
		return errors.New("signature verification FAILED")
	}

	// Phase 58 D-02 / R-2: pin OIDC issuer + SAN regex.
	//
	// TODO(maintainer): for strict tlog tree-head freshness (Q-1 in
	// 58-RESEARCH.md), call tr.RekorLogs() and assert the bundle's
	// inclusion proof references a tree-head no older than N hours.
	// Default behavior (SET-based offline check via WithTransparencyLog)
	// is sufficient per Q-1 default.
	v, err := verify.NewSignedEntityVerifier(tr,
		verify.WithSignedTimestamps(1),
		verify.WithTransparencyLog(1),
		verify.WithIntegratedTimestamps(1),
	)
	if err != nil {
		// canonical: signature verification FAILED — see Pitfall 4.
		return errors.New("signature verification FAILED")
	}

	identity, err := pinnedCertificateIdentity()
	if err != nil {
		// canonical: signature verification FAILED — see Pitfall 4.
		return errors.New("signature verification FAILED")
	}
	policy := verify.NewPolicy(
		verify.WithArtifact(bytes.NewReader(archiveBytes)),
		verify.WithCertificateIdentity(identity),
	)

	if _, err := v.Verify(b, policy); err != nil {
		if isRekorUnreachable(err) {
			// canonical: signature verification FAILED — see Pitfall 4.
			return fmt.Errorf("signature verification FAILED: Rekor transparency-log verification requires network access: %w", err)
		}
		// canonical: signature verification FAILED — see Pitfall 4.
		return errors.New("signature verification FAILED")
	}
	return nil
}

// pinnedCertificateIdentity constructs the sigstore-go CertificateIdentity
// pinned to the GitHub Actions OIDC issuer + agenthands/helix release.yml
// SAN regex. This is the SOLE source of truth for the verifier's identity
// policy: VerifyArchive's `verify.Verify` call is the only production
// path that exercises the pin, and the wrong-issuer / wrong-org
// fixture-driven tests in verify_test.go are the corresponding security
// regression guard. Per CR-01 (REVIEW.md), no parallel "testable mirror"
// is maintained — fixture-driven coverage is what prevents drift.
func pinnedCertificateIdentity() (verify.CertificateIdentity, error) {
	return verify.NewShortCertificateIdentity(
		pinnedOIDCIssuer,
		"",
		"",
		pinnedSANRegexLiteral,
	)
}

// isRekorUnreachable best-effort classifies whether err's chain looks
// like a network failure reaching Rekor (vs. a structural bundle error
// or signature mismatch). Used only to decide whether to surface the
// user-friendly D-04 wording on the wrapped error — false-negative is
// harmless (caller still gets the canonical literal).
func isRekorUnreachable(err error) bool {
	if err == nil {
		return false
	}
	// Direct net.OpError check.
	var opErr *net.OpError
	if errors.As(err, &opErr) {
		return true
	}
	// Substring match on the error chain. Rekor unreachable is best-effort
	// classified — false negatives are acceptable (the canonical literal
	// is still emitted), so we keep this check loose.
	msg := err.Error()
	for _, needle := range []string{
		"connection refused",
		"no such host",
		"network is unreachable",
		"i/o timeout",
		"context deadline exceeded",
		"dial tcp",
	} {
		if strings.Contains(msg, needle) {
			return true
		}
	}
	// testRekorURLOverride is only set in unit tests that want to force
	// the Rekor-unreachable branch. Honor it as a last-resort signal so
	// the test suite has a deterministic path to exercise the wording
	// without depending on real network behavior.
	if testRekorURLOverride != "" && strings.Contains(msg, testRekorURLOverride) {
		return true
	}
	return false
}
