// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/serena/v1/ipc.proto

package serenav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MCPMessage wraps a raw MCP JSON-RPC message for gRPC transport.
type MCPMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw MCP JSON-RPC message bytes (not parsed by forwarder).
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// Session identifier for routing within the daemon.
	SessionId     string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPMessage) Reset() {
	*x = MCPMessage{}
	mi := &file_api_proto_serena_v1_ipc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPMessage) ProtoMessage() {}

func (x *MCPMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_serena_v1_ipc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPMessage.ProtoReflect.Descriptor instead.
func (*MCPMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_serena_v1_ipc_proto_rawDescGZIP(), []int{0}
}

func (x *MCPMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MCPMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

var File_api_proto_serena_v1_ipc_proto protoreflect.FileDescriptor

const file_api_proto_serena_v1_ipc_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/serena/v1/ipc.proto\x12\tserena.v1\"E\n" +
	"\n" +
	"MCPMessage\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId2Q\n" +
	"\x10ForwarderService\x12=\n" +
	"\tStreamMCP\x12\x15.serena.v1.MCPMessage\x1a\x15.serena.v1.MCPMessage(\x010\x01B8Z6github.com/postfix/serena/api/proto/serena/v1;serenav1b\x06proto3"

var (
	file_api_proto_serena_v1_ipc_proto_rawDescOnce sync.Once
	file_api_proto_serena_v1_ipc_proto_rawDescData []byte
)

func file_api_proto_serena_v1_ipc_proto_rawDescGZIP() []byte {
	file_api_proto_serena_v1_ipc_proto_rawDescOnce.Do(func() {
		file_api_proto_serena_v1_ipc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_serena_v1_ipc_proto_rawDesc), len(file_api_proto_serena_v1_ipc_proto_rawDesc)))
	})
	return file_api_proto_serena_v1_ipc_proto_rawDescData
}

var file_api_proto_serena_v1_ipc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_proto_serena_v1_ipc_proto_goTypes = []any{
	(*MCPMessage)(nil), // 0: serena.v1.MCPMessage
}
var file_api_proto_serena_v1_ipc_proto_depIdxs = []int32{
	0, // 0: serena.v1.ForwarderService.StreamMCP:input_type -> serena.v1.MCPMessage
	0, // 1: serena.v1.ForwarderService.StreamMCP:output_type -> serena.v1.MCPMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_serena_v1_ipc_proto_init() }
func file_api_proto_serena_v1_ipc_proto_init() {
	if File_api_proto_serena_v1_ipc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_serena_v1_ipc_proto_rawDesc), len(file_api_proto_serena_v1_ipc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_serena_v1_ipc_proto_goTypes,
		DependencyIndexes: file_api_proto_serena_v1_ipc_proto_depIdxs,
		MessageInfos:      file_api_proto_serena_v1_ipc_proto_msgTypes,
	}.Build()
	File_api_proto_serena_v1_ipc_proto = out.File
	file_api_proto_serena_v1_ipc_proto_goTypes = nil
	file_api_proto_serena_v1_ipc_proto_depIdxs = nil
}
