// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/serena/v1/ipc.proto

package serenav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MCPMessage wraps a raw MCP JSON-RPC message for gRPC transport.
type MCPMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw MCP JSON-RPC message bytes (not parsed by forwarder).
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// Session identifier for routing within the daemon.
	SessionId     string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPMessage) Reset() {
	*x = MCPMessage{}
	mi := &file_api_proto_serena_v1_ipc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPMessage) ProtoMessage() {}

func (x *MCPMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_serena_v1_ipc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPMessage.ProtoReflect.Descriptor instead.
func (*MCPMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_serena_v1_ipc_proto_rawDescGZIP(), []int{0}
}

func (x *MCPMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MCPMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// StatusRequest queries daemon health.
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verbose       bool                   `protobuf:"varint,1,opt,name=verbose,proto3" json:"verbose,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_api_proto_serena_v1_ipc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_serena_v1_ipc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_serena_v1_ipc_proto_rawDescGZIP(), []int{1}
}

func (x *StatusRequest) GetVerbose() bool {
	if x != nil {
		return x.Verbose
	}
	return false
}

// StatusResponse carries JSON-encoded health report.
type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_api_proto_serena_v1_ipc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_serena_v1_ipc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_serena_v1_ipc_proto_rawDescGZIP(), []int{2}
}

func (x *StatusResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// ActivateRequest activates a workspace by path.
type ActivateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspacePath string                 `protobuf:"bytes,1,opt,name=workspace_path,json=workspacePath,proto3" json:"workspace_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateRequest) Reset() {
	*x = ActivateRequest{}
	mi := &file_api_proto_serena_v1_ipc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateRequest) ProtoMessage() {}

func (x *ActivateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_serena_v1_ipc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateRequest.ProtoReflect.Descriptor instead.
func (*ActivateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_serena_v1_ipc_proto_rawDescGZIP(), []int{3}
}

func (x *ActivateRequest) GetWorkspacePath() string {
	if x != nil {
		return x.WorkspacePath
	}
	return ""
}

// ActivateResponse reports activation result.
type ActivateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlreadyActive bool                   `protobuf:"varint,1,opt,name=already_active,json=alreadyActive,proto3" json:"already_active,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "activated" or "already_active"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateResponse) Reset() {
	*x = ActivateResponse{}
	mi := &file_api_proto_serena_v1_ipc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateResponse) ProtoMessage() {}

func (x *ActivateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_serena_v1_ipc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateResponse.ProtoReflect.Descriptor instead.
func (*ActivateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_serena_v1_ipc_proto_rawDescGZIP(), []int{4}
}

func (x *ActivateResponse) GetAlreadyActive() bool {
	if x != nil {
		return x.AlreadyActive
	}
	return false
}

func (x *ActivateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// DeactivateRequest deactivates a workspace by path.
type DeactivateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspacePath string                 `protobuf:"bytes,1,opt,name=workspace_path,json=workspacePath,proto3" json:"workspace_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateRequest) Reset() {
	*x = DeactivateRequest{}
	mi := &file_api_proto_serena_v1_ipc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateRequest) ProtoMessage() {}

func (x *DeactivateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_serena_v1_ipc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateRequest.ProtoReflect.Descriptor instead.
func (*DeactivateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_serena_v1_ipc_proto_rawDescGZIP(), []int{5}
}

func (x *DeactivateRequest) GetWorkspacePath() string {
	if x != nil {
		return x.WorkspacePath
	}
	return ""
}

// DeactivateResponse reports deactivation result.
type DeactivateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "deactivated" or "not_active"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateResponse) Reset() {
	*x = DeactivateResponse{}
	mi := &file_api_proto_serena_v1_ipc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateResponse) ProtoMessage() {}

func (x *DeactivateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_serena_v1_ipc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateResponse.ProtoReflect.Descriptor instead.
func (*DeactivateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_serena_v1_ipc_proto_rawDescGZIP(), []int{6}
}

func (x *DeactivateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_api_proto_serena_v1_ipc_proto protoreflect.FileDescriptor

const file_api_proto_serena_v1_ipc_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/serena/v1/ipc.proto\x12\tserena.v1\"E\n" +
	"\n" +
	"MCPMessage\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\")\n" +
	"\rStatusRequest\x12\x18\n" +
	"\averbose\x18\x01 \x01(\bR\averbose\"*\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"8\n" +
	"\x0fActivateRequest\x12%\n" +
	"\x0eworkspace_path\x18\x01 \x01(\tR\rworkspacePath\"Q\n" +
	"\x10ActivateResponse\x12%\n" +
	"\x0ealready_active\x18\x01 \x01(\bR\ralreadyActive\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\":\n" +
	"\x11DeactivateRequest\x12%\n" +
	"\x0eworkspace_path\x18\x01 \x01(\tR\rworkspacePath\",\n" +
	"\x12DeactivateResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xb5\x02\n" +
	"\x10ForwarderService\x12=\n" +
	"\tStreamMCP\x12\x15.serena.v1.MCPMessage\x1a\x15.serena.v1.MCPMessage(\x010\x01\x12@\n" +
	"\tGetStatus\x12\x18.serena.v1.StatusRequest\x1a\x19.serena.v1.StatusResponse\x12L\n" +
	"\x11ActivateWorkspace\x12\x1a.serena.v1.ActivateRequest\x1a\x1b.serena.v1.ActivateResponse\x12R\n" +
	"\x13DeactivateWorkspace\x12\x1c.serena.v1.DeactivateRequest\x1a\x1d.serena.v1.DeactivateResponseB8Z6github.com/postfix/serena/api/proto/serena/v1;serenav1b\x06proto3"

var (
	file_api_proto_serena_v1_ipc_proto_rawDescOnce sync.Once
	file_api_proto_serena_v1_ipc_proto_rawDescData []byte
)

func file_api_proto_serena_v1_ipc_proto_rawDescGZIP() []byte {
	file_api_proto_serena_v1_ipc_proto_rawDescOnce.Do(func() {
		file_api_proto_serena_v1_ipc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_serena_v1_ipc_proto_rawDesc), len(file_api_proto_serena_v1_ipc_proto_rawDesc)))
	})
	return file_api_proto_serena_v1_ipc_proto_rawDescData
}

var file_api_proto_serena_v1_ipc_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_serena_v1_ipc_proto_goTypes = []any{
	(*MCPMessage)(nil),         // 0: serena.v1.MCPMessage
	(*StatusRequest)(nil),      // 1: serena.v1.StatusRequest
	(*StatusResponse)(nil),     // 2: serena.v1.StatusResponse
	(*ActivateRequest)(nil),    // 3: serena.v1.ActivateRequest
	(*ActivateResponse)(nil),   // 4: serena.v1.ActivateResponse
	(*DeactivateRequest)(nil),  // 5: serena.v1.DeactivateRequest
	(*DeactivateResponse)(nil), // 6: serena.v1.DeactivateResponse
}
var file_api_proto_serena_v1_ipc_proto_depIdxs = []int32{
	0, // 0: serena.v1.ForwarderService.StreamMCP:input_type -> serena.v1.MCPMessage
	1, // 1: serena.v1.ForwarderService.GetStatus:input_type -> serena.v1.StatusRequest
	3, // 2: serena.v1.ForwarderService.ActivateWorkspace:input_type -> serena.v1.ActivateRequest
	5, // 3: serena.v1.ForwarderService.DeactivateWorkspace:input_type -> serena.v1.DeactivateRequest
	0, // 4: serena.v1.ForwarderService.StreamMCP:output_type -> serena.v1.MCPMessage
	2, // 5: serena.v1.ForwarderService.GetStatus:output_type -> serena.v1.StatusResponse
	4, // 6: serena.v1.ForwarderService.ActivateWorkspace:output_type -> serena.v1.ActivateResponse
	6, // 7: serena.v1.ForwarderService.DeactivateWorkspace:output_type -> serena.v1.DeactivateResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_serena_v1_ipc_proto_init() }
func file_api_proto_serena_v1_ipc_proto_init() {
	if File_api_proto_serena_v1_ipc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_serena_v1_ipc_proto_rawDesc), len(file_api_proto_serena_v1_ipc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_serena_v1_ipc_proto_goTypes,
		DependencyIndexes: file_api_proto_serena_v1_ipc_proto_depIdxs,
		MessageInfos:      file_api_proto_serena_v1_ipc_proto_msgTypes,
	}.Build()
	File_api_proto_serena_v1_ipc_proto = out.File
	file_api_proto_serena_v1_ipc_proto_goTypes = nil
	file_api_proto_serena_v1_ipc_proto_depIdxs = nil
}
