// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: api/proto/serena/v1/ipc.proto

package serenav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ForwarderService_StreamMCP_FullMethodName = "/serena.v1.ForwarderService/StreamMCP"
	ForwarderService_GetStatus_FullMethodName = "/serena.v1.ForwarderService/GetStatus"
)

// ForwarderServiceClient is the client API for ForwarderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ForwarderService handles bidirectional MCP message streaming
// between the stdio forwarder and the daemon process.
type ForwarderServiceClient interface {
	// StreamMCP carries MCP JSON-RPC messages bidirectionally.
	// Forwarder sends client messages, daemon sends responses.
	StreamMCP(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MCPMessage, MCPMessage], error)
	// GetStatus returns workspace health for the CLI status command.
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type forwarderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewForwarderServiceClient(cc grpc.ClientConnInterface) ForwarderServiceClient {
	return &forwarderServiceClient{cc}
}

func (c *forwarderServiceClient) StreamMCP(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MCPMessage, MCPMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ForwarderService_ServiceDesc.Streams[0], ForwarderService_StreamMCP_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MCPMessage, MCPMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ForwarderService_StreamMCPClient = grpc.BidiStreamingClient[MCPMessage, MCPMessage]

func (c *forwarderServiceClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, ForwarderService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ForwarderServiceServer is the server API for ForwarderService service.
// All implementations must embed UnimplementedForwarderServiceServer
// for forward compatibility.
//
// ForwarderService handles bidirectional MCP message streaming
// between the stdio forwarder and the daemon process.
type ForwarderServiceServer interface {
	// StreamMCP carries MCP JSON-RPC messages bidirectionally.
	// Forwarder sends client messages, daemon sends responses.
	StreamMCP(grpc.BidiStreamingServer[MCPMessage, MCPMessage]) error
	// GetStatus returns workspace health for the CLI status command.
	GetStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedForwarderServiceServer()
}

// UnimplementedForwarderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedForwarderServiceServer struct{}

func (UnimplementedForwarderServiceServer) StreamMCP(grpc.BidiStreamingServer[MCPMessage, MCPMessage]) error {
	return status.Error(codes.Unimplemented, "method StreamMCP not implemented")
}
func (UnimplementedForwarderServiceServer) GetStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedForwarderServiceServer) mustEmbedUnimplementedForwarderServiceServer() {}
func (UnimplementedForwarderServiceServer) testEmbeddedByValue()                          {}

// UnsafeForwarderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ForwarderServiceServer will
// result in compilation errors.
type UnsafeForwarderServiceServer interface {
	mustEmbedUnimplementedForwarderServiceServer()
}

func RegisterForwarderServiceServer(s grpc.ServiceRegistrar, srv ForwarderServiceServer) {
	// If the following call panics, it indicates UnimplementedForwarderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ForwarderService_ServiceDesc, srv)
}

func _ForwarderService_StreamMCP_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ForwarderServiceServer).StreamMCP(&grpc.GenericServerStream[MCPMessage, MCPMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ForwarderService_StreamMCPServer = grpc.BidiStreamingServer[MCPMessage, MCPMessage]

func _ForwarderService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwarderServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForwarderService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwarderServiceServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ForwarderService_ServiceDesc is the grpc.ServiceDesc for ForwarderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ForwarderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "serena.v1.ForwarderService",
	HandlerType: (*ForwarderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _ForwarderService_GetStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMCP",
			Handler:       _ForwarderService_StreamMCP_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/serena/v1/ipc.proto",
}
